// Code generated by girgen for GstController-1. DO NOT EDIT.

package gstcontroller

import (
	"fmt"
	"runtime"
	"unsafe"

	"github.com/go-gst/go-glib/pkg/core/transfer"
	"github.com/go-gst/go-glib/pkg/glib/v2"
	"github.com/go-gst/go-glib/pkg/gobject/v2"
	"github.com/go-gst/go-gst/pkg/gst"
)

// #cgo pkg-config: gstreamer-controller-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gst/controller/controller.h>
import "C"

// GType values.
var (
	TypeInterpolationMode          = gobject.Type(C.gst_interpolation_mode_get_type())
	TypeLFOWaveform                = gobject.Type(C.gst_lfo_waveform_get_type())
	TypeARGBControlBinding         = gobject.Type(C.gst_argb_control_binding_get_type())
	TypeDirectControlBinding       = gobject.Type(C.gst_direct_control_binding_get_type())
	TypeLFOControlSource           = gobject.Type(C.gst_lfo_control_source_get_type())
	TypeProxyControlBinding        = gobject.Type(C.gst_proxy_control_binding_get_type())
	TypeTimedValueControlSource    = gobject.Type(C.gst_timed_value_control_source_get_type())
	TypeTriggerControlSource       = gobject.Type(C.gst_trigger_control_source_get_type())
	TypeInterpolationControlSource = gobject.Type(C.gst_interpolation_control_source_get_type())
	TypeControlPoint               = gobject.Type(C.gst_control_point_get_type())
)

func init() {
	gobject.RegisterGValueMarshalers([]gobject.TypeMarshaler{
		gobject.TypeMarshaler{T: TypeInterpolationMode, F: marshalInterpolationMode},
		gobject.TypeMarshaler{T: TypeLFOWaveform, F: marshalLFOWaveform},
		gobject.TypeMarshaler{T: TypeARGBControlBinding, F: marshalARGBControlBindingInstance},
		gobject.TypeMarshaler{T: TypeDirectControlBinding, F: marshalDirectControlBindingInstance},
		gobject.TypeMarshaler{T: TypeLFOControlSource, F: marshalLFOControlSourceInstance},
		gobject.TypeMarshaler{T: TypeProxyControlBinding, F: marshalProxyControlBindingInstance},
		gobject.TypeMarshaler{T: TypeTimedValueControlSource, F: marshalTimedValueControlSourceInstance},
		gobject.TypeMarshaler{T: TypeTriggerControlSource, F: marshalTriggerControlSourceInstance},
		gobject.TypeMarshaler{T: TypeInterpolationControlSource, F: marshalInterpolationControlSourceInstance},
		gobject.TypeMarshaler{T: TypeControlPoint, F: marshalControlPoint},
	})
}

// InterpolationMode wraps GstInterpolationMode
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GstInterpolationMode
type InterpolationMode C.int

const (
	// InterpolationModeNone wraps GST_INTERPOLATION_MODE_NONE
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GST_INTERPOLATION_MODE_NONE
	InterpolationModeNone InterpolationMode = 0
	// InterpolationModeLinear wraps GST_INTERPOLATION_MODE_LINEAR
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GST_INTERPOLATION_MODE_LINEAR
	InterpolationModeLinear InterpolationMode = 1
	// InterpolationModeCubic wraps GST_INTERPOLATION_MODE_CUBIC
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GST_INTERPOLATION_MODE_CUBIC
	InterpolationModeCubic InterpolationMode = 2
	// InterpolationModeCubicMonotonic wraps GST_INTERPOLATION_MODE_CUBIC_MONOTONIC
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GST_INTERPOLATION_MODE_CUBIC_MONOTONIC
	InterpolationModeCubicMonotonic InterpolationMode = 3
)

func marshalInterpolationMode(p unsafe.Pointer) (any, error) {
	return InterpolationMode(gobject.ValueFromNative(p).Enum()), nil
}

var _ gobject.GoValueInitializer = InterpolationMode(0)

func (e InterpolationMode) GoValueType() gobject.Type {
	return TypeInterpolationMode
}

func (e InterpolationMode) SetGoValue(v *gobject.Value) {
	v.SetEnum(int32(e))
}

func (e InterpolationMode) String() string {
	switch e {
		case InterpolationModeCubic: return "InterpolationModeCubic"
		case InterpolationModeCubicMonotonic: return "InterpolationModeCubicMonotonic"
		case InterpolationModeLinear: return "InterpolationModeLinear"
		case InterpolationModeNone: return "InterpolationModeNone"
		default: return fmt.Sprintf("InterpolationMode(%d)", e)
	}
}

// LFOWaveform wraps GstLFOWaveform
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GstLFOWaveform
type LFOWaveform C.int

const (
	// LfoWaveformSine wraps GST_LFO_WAVEFORM_SINE
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GST_LFO_WAVEFORM_SINE
	LfoWaveformSine LFOWaveform = 0
	// LfoWaveformSquare wraps GST_LFO_WAVEFORM_SQUARE
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GST_LFO_WAVEFORM_SQUARE
	LfoWaveformSquare LFOWaveform = 1
	// LfoWaveformSaw wraps GST_LFO_WAVEFORM_SAW
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GST_LFO_WAVEFORM_SAW
	LfoWaveformSaw LFOWaveform = 2
	// LfoWaveformReverseSaw wraps GST_LFO_WAVEFORM_REVERSE_SAW
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GST_LFO_WAVEFORM_REVERSE_SAW
	LfoWaveformReverseSaw LFOWaveform = 3
	// LfoWaveformTriangle wraps GST_LFO_WAVEFORM_TRIANGLE
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GST_LFO_WAVEFORM_TRIANGLE
	LfoWaveformTriangle LFOWaveform = 4
)

func marshalLFOWaveform(p unsafe.Pointer) (any, error) {
	return LFOWaveform(gobject.ValueFromNative(p).Enum()), nil
}

var _ gobject.GoValueInitializer = LFOWaveform(0)

func (e LFOWaveform) GoValueType() gobject.Type {
	return TypeLFOWaveform
}

func (e LFOWaveform) SetGoValue(v *gobject.Value) {
	v.SetEnum(int32(e))
}

func (e LFOWaveform) String() string {
	switch e {
		case LfoWaveformReverseSaw: return "LfoWaveformReverseSaw"
		case LfoWaveformSaw: return "LfoWaveformSaw"
		case LfoWaveformSine: return "LfoWaveformSine"
		case LfoWaveformSquare: return "LfoWaveformSquare"
		case LfoWaveformTriangle: return "LfoWaveformTriangle"
		default: return fmt.Sprintf("LFOWaveform(%d)", e)
	}
}

// TimedValueControlInvalidateCache wraps gst_timed_value_control_invalidate_cache
// 
// see also https://gstreamer.freedesktop.org/documentation/controller
func TimedValueControlInvalidateCache(self TimedValueControlSource) {
	var carg1 *C.GstTimedValueControlSource // in, none, converted

	carg1 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))

	C.gst_timed_value_control_invalidate_cache(carg1)
	runtime.KeepAlive(self)
}

// ARGBControlBindingInstance is the instance type used by all types extending GstARGBControlBinding. It is used internally by the bindings. Users should use the interface [ARGBControlBinding] instead.
type ARGBControlBindingInstance struct {
	_ [0]func() // equal guard
	gst.ControlBindingInstance
}

var _ ARGBControlBinding = (*ARGBControlBindingInstance)(nil)

// ARGBControlBinding wraps GstARGBControlBinding
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstargbcontrolbinding.html#GstARGBControlBinding
type ARGBControlBinding interface {
	gst.ControlBinding
	upcastToGstARGBControlBinding() *ARGBControlBindingInstance

	// chain up virtual methods:
}

func unsafeWrapARGBControlBinding(base *gobject.ObjectInstance) *ARGBControlBindingInstance {
	return &ARGBControlBindingInstance{
		ControlBindingInstance: gst.ControlBindingInstance{
			ObjectInstance: gst.ObjectInstance{
				InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
					ObjectInstance: *base,
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeARGBControlBinding,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapARGBControlBinding(inst)
		},
	)
}

func marshalARGBControlBindingInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeARGBControlBindingFromGlibNone is used to convert raw GstARGBControlBinding pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeARGBControlBindingFromGlibNone(c unsafe.Pointer) ARGBControlBinding {
	return gobject.UnsafeObjectFromGlibNone(c).(ARGBControlBinding)
}

// UnsafeARGBControlBindingFromGlibFull is used to convert raw GstARGBControlBinding pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeARGBControlBindingFromGlibFull(c unsafe.Pointer) ARGBControlBinding {
	return gobject.UnsafeObjectFromGlibFull(c).(ARGBControlBinding)
}

// UnsafeARGBControlBindingFromGlibBorrow is used to convert raw GstARGBControlBinding pointers to go without touching any references. This is used by the bindings internally.
func UnsafeARGBControlBindingFromGlibBorrow(c unsafe.Pointer) ARGBControlBinding {
	return gobject.UnsafeObjectFromGlibBorrow(c).(ARGBControlBinding)
}

func (a *ARGBControlBindingInstance) upcastToGstARGBControlBinding() *ARGBControlBindingInstance {
	return a
}

// UnsafeARGBControlBindingToGlibNone is used to convert the instance to it's C value GstARGBControlBinding. This is used by the bindings internally.
func UnsafeARGBControlBindingToGlibNone(c ARGBControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeARGBControlBindingToGlibFull is used to convert the instance to it's C value GstARGBControlBinding, while removeing the finalizer. This is used by the bindings internally.
func UnsafeARGBControlBindingToGlibFull(c ARGBControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewARGBControlBinding wraps gst_argb_control_binding_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstargbcontrolbinding.html#gst_argb_control_binding_new
func NewARGBControlBinding(object gst.Object, propertyName string, csA gst.ControlSource, csR gst.ControlSource, csG gst.ControlSource, csB gst.ControlSource) gst.ControlBinding {
	var carg1 *C.GstObject         // in, none, converted
	var carg2 *C.gchar             // in, none, string
	var carg3 *C.GstControlSource  // in, none, converted
	var carg4 *C.GstControlSource  // in, none, converted
	var carg5 *C.GstControlSource  // in, none, converted
	var carg6 *C.GstControlSource  // in, none, converted
	var cret  *C.GstControlBinding // return, none, converted

	carg1 = (*C.GstObject)(gst.UnsafeObjectToGlibNone(object))
	carg2 = (*C.gchar)(transfer.GLibString(propertyName))
	defer C.g_free(C.gpointer(carg2))
	carg3 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(csA))
	carg4 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(csR))
	carg5 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(csG))
	carg6 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(csB))

	cret = C.gst_argb_control_binding_new(carg1, carg2, carg3, carg4, carg5, carg6)
	runtime.KeepAlive(object)
	runtime.KeepAlive(propertyName)
	runtime.KeepAlive(csA)
	runtime.KeepAlive(csR)
	runtime.KeepAlive(csG)
	runtime.KeepAlive(csB)

	var goret gst.ControlBinding

	goret = gst.UnsafeControlBindingFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// ARGBControlBindingOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type ARGBControlBindingOverrides[Instance ARGBControlBinding] struct {
	// gst.ControlBindingOverrides allows you to override virtual methods from the parent class gst.ControlBinding
	gst.ControlBindingOverrides[Instance]

}

// UnsafeApplyARGBControlBindingOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyARGBControlBindingOverrides[Instance ARGBControlBinding](gclass unsafe.Pointer, overrides ARGBControlBindingOverrides[Instance]) {
	gst.UnsafeApplyControlBindingOverrides(gclass, overrides.ControlBindingOverrides)
}

// RegisterARGBControlBindingSubClass is used to register a go subclass of GstARGBControlBinding. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterARGBControlBindingSubClass[InstanceT ARGBControlBinding](
		name string,
		classInit func(class *ARGBControlBindingClass),
		constructor func() InstanceT,
		overrides ARGBControlBindingOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeARGBControlBinding,
		UnsafeARGBControlBindingClassFromGlibBorrow,
		UnsafeApplyARGBControlBindingOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapARGBControlBinding(obj)
		},
		interfaceInits...,
	)
}

// DirectControlBindingInstance is the instance type used by all types extending GstDirectControlBinding. It is used internally by the bindings. Users should use the interface [DirectControlBinding] instead.
type DirectControlBindingInstance struct {
	_ [0]func() // equal guard
	gst.ControlBindingInstance
}

var _ DirectControlBinding = (*DirectControlBindingInstance)(nil)

// DirectControlBinding wraps GstDirectControlBinding
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstdirectcontrolbinding.html#GstDirectControlBinding
type DirectControlBinding interface {
	gst.ControlBinding
	upcastToGstDirectControlBinding() *DirectControlBindingInstance

	// chain up virtual methods:
}

func unsafeWrapDirectControlBinding(base *gobject.ObjectInstance) *DirectControlBindingInstance {
	return &DirectControlBindingInstance{
		ControlBindingInstance: gst.ControlBindingInstance{
			ObjectInstance: gst.ObjectInstance{
				InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
					ObjectInstance: *base,
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeDirectControlBinding,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapDirectControlBinding(inst)
		},
	)
}

func marshalDirectControlBindingInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeDirectControlBindingFromGlibNone is used to convert raw GstDirectControlBinding pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeDirectControlBindingFromGlibNone(c unsafe.Pointer) DirectControlBinding {
	return gobject.UnsafeObjectFromGlibNone(c).(DirectControlBinding)
}

// UnsafeDirectControlBindingFromGlibFull is used to convert raw GstDirectControlBinding pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeDirectControlBindingFromGlibFull(c unsafe.Pointer) DirectControlBinding {
	return gobject.UnsafeObjectFromGlibFull(c).(DirectControlBinding)
}

// UnsafeDirectControlBindingFromGlibBorrow is used to convert raw GstDirectControlBinding pointers to go without touching any references. This is used by the bindings internally.
func UnsafeDirectControlBindingFromGlibBorrow(c unsafe.Pointer) DirectControlBinding {
	return gobject.UnsafeObjectFromGlibBorrow(c).(DirectControlBinding)
}

func (d *DirectControlBindingInstance) upcastToGstDirectControlBinding() *DirectControlBindingInstance {
	return d
}

// UnsafeDirectControlBindingToGlibNone is used to convert the instance to it's C value GstDirectControlBinding. This is used by the bindings internally.
func UnsafeDirectControlBindingToGlibNone(c DirectControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeDirectControlBindingToGlibFull is used to convert the instance to it's C value GstDirectControlBinding, while removeing the finalizer. This is used by the bindings internally.
func UnsafeDirectControlBindingToGlibFull(c DirectControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewDirectControlBinding wraps gst_direct_control_binding_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstdirectcontrolbinding.html#gst_direct_control_binding_new
func NewDirectControlBinding(object gst.Object, propertyName string, cs gst.ControlSource) gst.ControlBinding {
	var carg1 *C.GstObject         // in, none, converted
	var carg2 *C.gchar             // in, none, string
	var carg3 *C.GstControlSource  // in, none, converted
	var cret  *C.GstControlBinding // return, none, converted

	carg1 = (*C.GstObject)(gst.UnsafeObjectToGlibNone(object))
	carg2 = (*C.gchar)(transfer.GLibString(propertyName))
	defer C.g_free(C.gpointer(carg2))
	carg3 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(cs))

	cret = C.gst_direct_control_binding_new(carg1, carg2, carg3)
	runtime.KeepAlive(object)
	runtime.KeepAlive(propertyName)
	runtime.KeepAlive(cs)

	var goret gst.ControlBinding

	goret = gst.UnsafeControlBindingFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// NewDirectControlBindingAbsolute wraps gst_direct_control_binding_new_absolute
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstdirectcontrolbinding.html#gst_direct_control_binding_new_absolute
func NewDirectControlBindingAbsolute(object gst.Object, propertyName string, cs gst.ControlSource) gst.ControlBinding {
	var carg1 *C.GstObject         // in, none, converted
	var carg2 *C.gchar             // in, none, string
	var carg3 *C.GstControlSource  // in, none, converted
	var cret  *C.GstControlBinding // return, none, converted

	carg1 = (*C.GstObject)(gst.UnsafeObjectToGlibNone(object))
	carg2 = (*C.gchar)(transfer.GLibString(propertyName))
	defer C.g_free(C.gpointer(carg2))
	carg3 = (*C.GstControlSource)(gst.UnsafeControlSourceToGlibNone(cs))

	cret = C.gst_direct_control_binding_new_absolute(carg1, carg2, carg3)
	runtime.KeepAlive(object)
	runtime.KeepAlive(propertyName)
	runtime.KeepAlive(cs)

	var goret gst.ControlBinding

	goret = gst.UnsafeControlBindingFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// DirectControlBindingOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type DirectControlBindingOverrides[Instance DirectControlBinding] struct {
	// gst.ControlBindingOverrides allows you to override virtual methods from the parent class gst.ControlBinding
	gst.ControlBindingOverrides[Instance]

}

// UnsafeApplyDirectControlBindingOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyDirectControlBindingOverrides[Instance DirectControlBinding](gclass unsafe.Pointer, overrides DirectControlBindingOverrides[Instance]) {
	gst.UnsafeApplyControlBindingOverrides(gclass, overrides.ControlBindingOverrides)
}

// RegisterDirectControlBindingSubClass is used to register a go subclass of GstDirectControlBinding. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterDirectControlBindingSubClass[InstanceT DirectControlBinding](
		name string,
		classInit func(class *DirectControlBindingClass),
		constructor func() InstanceT,
		overrides DirectControlBindingOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeDirectControlBinding,
		UnsafeDirectControlBindingClassFromGlibBorrow,
		UnsafeApplyDirectControlBindingOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapDirectControlBinding(obj)
		},
		interfaceInits...,
	)
}

// LFOControlSourceInstance is the instance type used by all types extending GstLFOControlSource. It is used internally by the bindings. Users should use the interface [LFOControlSource] instead.
type LFOControlSourceInstance struct {
	_ [0]func() // equal guard
	gst.ControlSourceInstance
}

var _ LFOControlSource = (*LFOControlSourceInstance)(nil)

// LFOControlSource wraps GstLFOControlSource
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GstLFOControlSource
type LFOControlSource interface {
	gst.ControlSource
	upcastToGstLFOControlSource() *LFOControlSourceInstance

	// chain up virtual methods:
}

func unsafeWrapLFOControlSource(base *gobject.ObjectInstance) *LFOControlSourceInstance {
	return &LFOControlSourceInstance{
		ControlSourceInstance: gst.ControlSourceInstance{
			ObjectInstance: gst.ObjectInstance{
				InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
					ObjectInstance: *base,
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeLFOControlSource,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapLFOControlSource(inst)
		},
	)
}

func marshalLFOControlSourceInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeLFOControlSourceFromGlibNone is used to convert raw GstLFOControlSource pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeLFOControlSourceFromGlibNone(c unsafe.Pointer) LFOControlSource {
	return gobject.UnsafeObjectFromGlibNone(c).(LFOControlSource)
}

// UnsafeLFOControlSourceFromGlibFull is used to convert raw GstLFOControlSource pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeLFOControlSourceFromGlibFull(c unsafe.Pointer) LFOControlSource {
	return gobject.UnsafeObjectFromGlibFull(c).(LFOControlSource)
}

// UnsafeLFOControlSourceFromGlibBorrow is used to convert raw GstLFOControlSource pointers to go without touching any references. This is used by the bindings internally.
func UnsafeLFOControlSourceFromGlibBorrow(c unsafe.Pointer) LFOControlSource {
	return gobject.UnsafeObjectFromGlibBorrow(c).(LFOControlSource)
}

func (l *LFOControlSourceInstance) upcastToGstLFOControlSource() *LFOControlSourceInstance {
	return l
}

// UnsafeLFOControlSourceToGlibNone is used to convert the instance to it's C value GstLFOControlSource. This is used by the bindings internally.
func UnsafeLFOControlSourceToGlibNone(c LFOControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeLFOControlSourceToGlibFull is used to convert the instance to it's C value GstLFOControlSource, while removeing the finalizer. This is used by the bindings internally.
func UnsafeLFOControlSourceToGlibFull(c LFOControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewLFOControlSource wraps gst_lfo_control_source_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#gst_lfo_control_source_new
func NewLFOControlSource() gst.ControlSource {
	var cret *C.GstControlSource // return, full, converted

	cret = C.gst_lfo_control_source_new()

	var goret gst.ControlSource

	goret = gst.UnsafeControlSourceFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// LFOControlSourceOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type LFOControlSourceOverrides[Instance LFOControlSource] struct {
	// gst.ControlSourceOverrides allows you to override virtual methods from the parent class gst.ControlSource
	gst.ControlSourceOverrides[Instance]

}

// UnsafeApplyLFOControlSourceOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyLFOControlSourceOverrides[Instance LFOControlSource](gclass unsafe.Pointer, overrides LFOControlSourceOverrides[Instance]) {
	gst.UnsafeApplyControlSourceOverrides(gclass, overrides.ControlSourceOverrides)
}

// RegisterLFOControlSourceSubClass is used to register a go subclass of GstLFOControlSource. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterLFOControlSourceSubClass[InstanceT LFOControlSource](
		name string,
		classInit func(class *LFOControlSourceClass),
		constructor func() InstanceT,
		overrides LFOControlSourceOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeLFOControlSource,
		UnsafeLFOControlSourceClassFromGlibBorrow,
		UnsafeApplyLFOControlSourceOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapLFOControlSource(obj)
		},
		interfaceInits...,
	)
}

// ProxyControlBindingInstance is the instance type used by all types extending GstProxyControlBinding. It is used internally by the bindings. Users should use the interface [ProxyControlBinding] instead.
type ProxyControlBindingInstance struct {
	_ [0]func() // equal guard
	gst.ControlBindingInstance
}

var _ ProxyControlBinding = (*ProxyControlBindingInstance)(nil)

// ProxyControlBinding wraps GstProxyControlBinding
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstproxycontrolbinding.html#GstProxyControlBinding
type ProxyControlBinding interface {
	gst.ControlBinding
	upcastToGstProxyControlBinding() *ProxyControlBindingInstance

	// chain up virtual methods:
}

func unsafeWrapProxyControlBinding(base *gobject.ObjectInstance) *ProxyControlBindingInstance {
	return &ProxyControlBindingInstance{
		ControlBindingInstance: gst.ControlBindingInstance{
			ObjectInstance: gst.ObjectInstance{
				InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
					ObjectInstance: *base,
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeProxyControlBinding,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapProxyControlBinding(inst)
		},
	)
}

func marshalProxyControlBindingInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeProxyControlBindingFromGlibNone is used to convert raw GstProxyControlBinding pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeProxyControlBindingFromGlibNone(c unsafe.Pointer) ProxyControlBinding {
	return gobject.UnsafeObjectFromGlibNone(c).(ProxyControlBinding)
}

// UnsafeProxyControlBindingFromGlibFull is used to convert raw GstProxyControlBinding pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeProxyControlBindingFromGlibFull(c unsafe.Pointer) ProxyControlBinding {
	return gobject.UnsafeObjectFromGlibFull(c).(ProxyControlBinding)
}

// UnsafeProxyControlBindingFromGlibBorrow is used to convert raw GstProxyControlBinding pointers to go without touching any references. This is used by the bindings internally.
func UnsafeProxyControlBindingFromGlibBorrow(c unsafe.Pointer) ProxyControlBinding {
	return gobject.UnsafeObjectFromGlibBorrow(c).(ProxyControlBinding)
}

func (p *ProxyControlBindingInstance) upcastToGstProxyControlBinding() *ProxyControlBindingInstance {
	return p
}

// UnsafeProxyControlBindingToGlibNone is used to convert the instance to it's C value GstProxyControlBinding. This is used by the bindings internally.
func UnsafeProxyControlBindingToGlibNone(c ProxyControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeProxyControlBindingToGlibFull is used to convert the instance to it's C value GstProxyControlBinding, while removeing the finalizer. This is used by the bindings internally.
func UnsafeProxyControlBindingToGlibFull(c ProxyControlBinding) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewProxyControlBinding wraps gst_proxy_control_binding_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstproxycontrolbinding.html#gst_proxy_control_binding_new
func NewProxyControlBinding(object gst.Object, propertyName string, refObject gst.Object, refPropertyName string) gst.ControlBinding {
	var carg1 *C.GstObject         // in, none, converted
	var carg2 *C.gchar             // in, none, string
	var carg3 *C.GstObject         // in, none, converted
	var carg4 *C.gchar             // in, none, string
	var cret  *C.GstControlBinding // return, none, converted

	carg1 = (*C.GstObject)(gst.UnsafeObjectToGlibNone(object))
	carg2 = (*C.gchar)(transfer.GLibString(propertyName))
	defer C.g_free(C.gpointer(carg2))
	carg3 = (*C.GstObject)(gst.UnsafeObjectToGlibNone(refObject))
	carg4 = (*C.gchar)(transfer.GLibString(refPropertyName))
	defer C.g_free(C.gpointer(carg4))

	cret = C.gst_proxy_control_binding_new(carg1, carg2, carg3, carg4)
	runtime.KeepAlive(object)
	runtime.KeepAlive(propertyName)
	runtime.KeepAlive(refObject)
	runtime.KeepAlive(refPropertyName)

	var goret gst.ControlBinding

	goret = gst.UnsafeControlBindingFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// ProxyControlBindingOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type ProxyControlBindingOverrides[Instance ProxyControlBinding] struct {
	// gst.ControlBindingOverrides allows you to override virtual methods from the parent class gst.ControlBinding
	gst.ControlBindingOverrides[Instance]

}

// UnsafeApplyProxyControlBindingOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyProxyControlBindingOverrides[Instance ProxyControlBinding](gclass unsafe.Pointer, overrides ProxyControlBindingOverrides[Instance]) {
	gst.UnsafeApplyControlBindingOverrides(gclass, overrides.ControlBindingOverrides)
}

// RegisterProxyControlBindingSubClass is used to register a go subclass of GstProxyControlBinding. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterProxyControlBindingSubClass[InstanceT ProxyControlBinding](
		name string,
		classInit func(class *ProxyControlBindingClass),
		constructor func() InstanceT,
		overrides ProxyControlBindingOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeProxyControlBinding,
		UnsafeProxyControlBindingClassFromGlibBorrow,
		UnsafeApplyProxyControlBindingOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapProxyControlBinding(obj)
		},
		interfaceInits...,
	)
}

// TimedValueControlSourceInstance is the instance type used by all types extending GstTimedValueControlSource. It is used internally by the bindings. Users should use the interface [TimedValueControlSource] instead.
type TimedValueControlSourceInstance struct {
	_ [0]func() // equal guard
	gst.ControlSourceInstance
}

var _ TimedValueControlSource = (*TimedValueControlSourceInstance)(nil)

// TimedValueControlSource wraps GstTimedValueControlSource
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#GstTimedValueControlSource
type TimedValueControlSource interface {
	gst.ControlSource
	upcastToGstTimedValueControlSource() *TimedValueControlSourceInstance

	// FindControlPointIter wraps gst_timed_value_control_source_find_control_point_iter
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_find_control_point_iter
	FindControlPointIter(gst.ClockTime) *glib.SequenceIter
	// GetAll wraps gst_timed_value_control_source_get_all
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_get_all
	GetAll() []*gst.TimedValue
	// GetCount wraps gst_timed_value_control_source_get_count
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_get_count
	GetCount() int32
	// Set wraps gst_timed_value_control_source_set
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_set
	Set(gst.ClockTime, float64) bool
	// Unset wraps gst_timed_value_control_source_unset
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_unset
	Unset(gst.ClockTime) bool
	// UnsetAll wraps gst_timed_value_control_source_unset_all
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_unset_all
	UnsetAll()
	// ConnectValueAdded connects the provided callback to the "value-added" signal
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
	ConnectValueAdded(func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle
	// ConnectValueChanged connects the provided callback to the "value-changed" signal
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
	ConnectValueChanged(func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle
	// ConnectValueRemoved connects the provided callback to the "value-removed" signal
	// 
	// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
	ConnectValueRemoved(func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle

	// chain up virtual methods:
}

func unsafeWrapTimedValueControlSource(base *gobject.ObjectInstance) *TimedValueControlSourceInstance {
	return &TimedValueControlSourceInstance{
		ControlSourceInstance: gst.ControlSourceInstance{
			ObjectInstance: gst.ObjectInstance{
				InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
					ObjectInstance: *base,
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeTimedValueControlSource,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapTimedValueControlSource(inst)
		},
	)
}

func marshalTimedValueControlSourceInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeTimedValueControlSourceFromGlibNone is used to convert raw GstTimedValueControlSource pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeTimedValueControlSourceFromGlibNone(c unsafe.Pointer) TimedValueControlSource {
	return gobject.UnsafeObjectFromGlibNone(c).(TimedValueControlSource)
}

// UnsafeTimedValueControlSourceFromGlibFull is used to convert raw GstTimedValueControlSource pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeTimedValueControlSourceFromGlibFull(c unsafe.Pointer) TimedValueControlSource {
	return gobject.UnsafeObjectFromGlibFull(c).(TimedValueControlSource)
}

// UnsafeTimedValueControlSourceFromGlibBorrow is used to convert raw GstTimedValueControlSource pointers to go without touching any references. This is used by the bindings internally.
func UnsafeTimedValueControlSourceFromGlibBorrow(c unsafe.Pointer) TimedValueControlSource {
	return gobject.UnsafeObjectFromGlibBorrow(c).(TimedValueControlSource)
}

func (t *TimedValueControlSourceInstance) upcastToGstTimedValueControlSource() *TimedValueControlSourceInstance {
	return t
}

// UnsafeTimedValueControlSourceToGlibNone is used to convert the instance to it's C value GstTimedValueControlSource. This is used by the bindings internally.
func UnsafeTimedValueControlSourceToGlibNone(c TimedValueControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeTimedValueControlSourceToGlibFull is used to convert the instance to it's C value GstTimedValueControlSource, while removeing the finalizer. This is used by the bindings internally.
func UnsafeTimedValueControlSourceToGlibFull(c TimedValueControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// FindControlPointIter wraps gst_timed_value_control_source_find_control_point_iter
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_find_control_point_iter
func (self *TimedValueControlSourceInstance) FindControlPointIter(timestamp gst.ClockTime) *glib.SequenceIter {
	var carg0 *C.GstTimedValueControlSource // in, none, converted
	var carg1 C.GstClockTime                // in, none, casted, alias
	var cret  *C.GSequenceIter              // return, none, converted, nullable

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))
	carg1 = C.GstClockTime(timestamp)

	cret = C.gst_timed_value_control_source_find_control_point_iter(carg0, carg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(timestamp)

	var goret *glib.SequenceIter

	if cret != nil {
		goret = glib.UnsafeSequenceIterFromGlibNone(unsafe.Pointer(cret))
	}

	return goret
}

// GetAll wraps gst_timed_value_control_source_get_all
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_get_all
func (self *TimedValueControlSourceInstance) GetAll() []*gst.TimedValue {
	var carg0 *C.GstTimedValueControlSource // in, none, converted
	var cret  *C.GList                      // container, transfer: container

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))

	cret = C.gst_timed_value_control_source_get_all(carg0)
	runtime.KeepAlive(self)

	var goret []*gst.TimedValue

	goret = glib.UnsafeListFromGlibFull(
		unsafe.Pointer(cret),
		func(v unsafe.Pointer) *gst.TimedValue {
			var dst *gst.TimedValue // converted
			dst = gst.UnsafeTimedValueFromGlibNone(v)
			return dst
		},
	)

	return goret
}

// GetCount wraps gst_timed_value_control_source_get_count
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_get_count
func (self *TimedValueControlSourceInstance) GetCount() int32 {
	var carg0 *C.GstTimedValueControlSource // in, none, converted
	var cret  C.gint                        // return, none, casted

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))

	cret = C.gst_timed_value_control_source_get_count(carg0)
	runtime.KeepAlive(self)

	var goret int32

	goret = int32(cret)

	return goret
}

// Set wraps gst_timed_value_control_source_set
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_set
func (self *TimedValueControlSourceInstance) Set(timestamp gst.ClockTime, value float64) bool {
	var carg0 *C.GstTimedValueControlSource // in, none, converted
	var carg1 C.GstClockTime                // in, none, casted, alias
	var carg2 C.gdouble                     // in, none, casted
	var cret  C.gboolean                    // return

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))
	carg1 = C.GstClockTime(timestamp)
	carg2 = C.gdouble(value)

	cret = C.gst_timed_value_control_source_set(carg0, carg1, carg2)
	runtime.KeepAlive(self)
	runtime.KeepAlive(timestamp)
	runtime.KeepAlive(value)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// Unset wraps gst_timed_value_control_source_unset
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_unset
func (self *TimedValueControlSourceInstance) Unset(timestamp gst.ClockTime) bool {
	var carg0 *C.GstTimedValueControlSource // in, none, converted
	var carg1 C.GstClockTime                // in, none, casted, alias
	var cret  C.gboolean                    // return

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))
	carg1 = C.GstClockTime(timestamp)

	cret = C.gst_timed_value_control_source_unset(carg0, carg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(timestamp)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// UnsetAll wraps gst_timed_value_control_source_unset_all
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_timed_value_control_source_unset_all
func (self *TimedValueControlSourceInstance) UnsetAll() {
	var carg0 *C.GstTimedValueControlSource // in, none, converted

	carg0 = (*C.GstTimedValueControlSource)(UnsafeTimedValueControlSourceToGlibNone(self))

	C.gst_timed_value_control_source_unset_all(carg0)
	runtime.KeepAlive(self)
}

// ConnectValueAdded connects the provided callback to the "value-added" signal
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
func (o *TimedValueControlSourceInstance) ConnectValueAdded(fn func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle {
	return o.Connect("value-added", fn)
}

// ConnectValueChanged connects the provided callback to the "value-changed" signal
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
func (o *TimedValueControlSourceInstance) ConnectValueChanged(fn func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle {
	return o.Connect("value-changed", fn)
}

// ConnectValueRemoved connects the provided callback to the "value-removed" signal
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html
func (o *TimedValueControlSourceInstance) ConnectValueRemoved(fn func(TimedValueControlSource, *ControlPoint)) gobject.SignalHandle {
	return o.Connect("value-removed", fn)
}

// TimedValueControlSourceOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type TimedValueControlSourceOverrides[Instance TimedValueControlSource] struct {
	// gst.ControlSourceOverrides allows you to override virtual methods from the parent class gst.ControlSource
	gst.ControlSourceOverrides[Instance]

}

// UnsafeApplyTimedValueControlSourceOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyTimedValueControlSourceOverrides[Instance TimedValueControlSource](gclass unsafe.Pointer, overrides TimedValueControlSourceOverrides[Instance]) {
	gst.UnsafeApplyControlSourceOverrides(gclass, overrides.ControlSourceOverrides)
}

// RegisterTimedValueControlSourceSubClass is used to register a go subclass of GstTimedValueControlSource. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterTimedValueControlSourceSubClass[InstanceT TimedValueControlSource](
		name string,
		classInit func(class *TimedValueControlSourceClass),
		constructor func() InstanceT,
		overrides TimedValueControlSourceOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeTimedValueControlSource,
		UnsafeTimedValueControlSourceClassFromGlibBorrow,
		UnsafeApplyTimedValueControlSourceOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapTimedValueControlSource(obj)
		},
		interfaceInits...,
	)
}

// TriggerControlSourceInstance is the instance type used by all types extending GstTriggerControlSource. It is used internally by the bindings. Users should use the interface [TriggerControlSource] instead.
type TriggerControlSourceInstance struct {
	_ [0]func() // equal guard
	TimedValueControlSourceInstance
}

var _ TriggerControlSource = (*TriggerControlSourceInstance)(nil)

// TriggerControlSource wraps GstTriggerControlSource
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttriggercontrolsource.html#GstTriggerControlSource
type TriggerControlSource interface {
	TimedValueControlSource
	upcastToGstTriggerControlSource() *TriggerControlSourceInstance

	// chain up virtual methods:
}

func unsafeWrapTriggerControlSource(base *gobject.ObjectInstance) *TriggerControlSourceInstance {
	return &TriggerControlSourceInstance{
		TimedValueControlSourceInstance: TimedValueControlSourceInstance{
			ControlSourceInstance: gst.ControlSourceInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeTriggerControlSource,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapTriggerControlSource(inst)
		},
	)
}

func marshalTriggerControlSourceInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeTriggerControlSourceFromGlibNone is used to convert raw GstTriggerControlSource pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeTriggerControlSourceFromGlibNone(c unsafe.Pointer) TriggerControlSource {
	return gobject.UnsafeObjectFromGlibNone(c).(TriggerControlSource)
}

// UnsafeTriggerControlSourceFromGlibFull is used to convert raw GstTriggerControlSource pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeTriggerControlSourceFromGlibFull(c unsafe.Pointer) TriggerControlSource {
	return gobject.UnsafeObjectFromGlibFull(c).(TriggerControlSource)
}

// UnsafeTriggerControlSourceFromGlibBorrow is used to convert raw GstTriggerControlSource pointers to go without touching any references. This is used by the bindings internally.
func UnsafeTriggerControlSourceFromGlibBorrow(c unsafe.Pointer) TriggerControlSource {
	return gobject.UnsafeObjectFromGlibBorrow(c).(TriggerControlSource)
}

func (t *TriggerControlSourceInstance) upcastToGstTriggerControlSource() *TriggerControlSourceInstance {
	return t
}

// UnsafeTriggerControlSourceToGlibNone is used to convert the instance to it's C value GstTriggerControlSource. This is used by the bindings internally.
func UnsafeTriggerControlSourceToGlibNone(c TriggerControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeTriggerControlSourceToGlibFull is used to convert the instance to it's C value GstTriggerControlSource, while removeing the finalizer. This is used by the bindings internally.
func UnsafeTriggerControlSourceToGlibFull(c TriggerControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewTriggerControlSource wraps gst_trigger_control_source_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttriggercontrolsource.html#gst_trigger_control_source_new
func NewTriggerControlSource() gst.ControlSource {
	var cret *C.GstControlSource // return, full, converted

	cret = C.gst_trigger_control_source_new()

	var goret gst.ControlSource

	goret = gst.UnsafeControlSourceFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// TriggerControlSourceOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type TriggerControlSourceOverrides[Instance TriggerControlSource] struct {
	// TimedValueControlSourceOverrides allows you to override virtual methods from the parent class TimedValueControlSource
	TimedValueControlSourceOverrides[Instance]

}

// UnsafeApplyTriggerControlSourceOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyTriggerControlSourceOverrides[Instance TriggerControlSource](gclass unsafe.Pointer, overrides TriggerControlSourceOverrides[Instance]) {
	UnsafeApplyTimedValueControlSourceOverrides(gclass, overrides.TimedValueControlSourceOverrides)
}

// RegisterTriggerControlSourceSubClass is used to register a go subclass of GstTriggerControlSource. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterTriggerControlSourceSubClass[InstanceT TriggerControlSource](
		name string,
		classInit func(class *TriggerControlSourceClass),
		constructor func() InstanceT,
		overrides TriggerControlSourceOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeTriggerControlSource,
		UnsafeTriggerControlSourceClassFromGlibBorrow,
		UnsafeApplyTriggerControlSourceOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapTriggerControlSource(obj)
		},
		interfaceInits...,
	)
}

// InterpolationControlSourceInstance is the instance type used by all types extending GstInterpolationControlSource. It is used internally by the bindings. Users should use the interface [InterpolationControlSource] instead.
type InterpolationControlSourceInstance struct {
	_ [0]func() // equal guard
	TimedValueControlSourceInstance
}

var _ InterpolationControlSource = (*InterpolationControlSourceInstance)(nil)

// InterpolationControlSource wraps GstInterpolationControlSource
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GstInterpolationControlSource
type InterpolationControlSource interface {
	TimedValueControlSource
	upcastToGstInterpolationControlSource() *InterpolationControlSourceInstance

	// chain up virtual methods:
}

func unsafeWrapInterpolationControlSource(base *gobject.ObjectInstance) *InterpolationControlSourceInstance {
	return &InterpolationControlSourceInstance{
		TimedValueControlSourceInstance: TimedValueControlSourceInstance{
			ControlSourceInstance: gst.ControlSourceInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeInterpolationControlSource,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapInterpolationControlSource(inst)
		},
	)
}

func marshalInterpolationControlSourceInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeInterpolationControlSourceFromGlibNone is used to convert raw GstInterpolationControlSource pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeInterpolationControlSourceFromGlibNone(c unsafe.Pointer) InterpolationControlSource {
	return gobject.UnsafeObjectFromGlibNone(c).(InterpolationControlSource)
}

// UnsafeInterpolationControlSourceFromGlibFull is used to convert raw GstInterpolationControlSource pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeInterpolationControlSourceFromGlibFull(c unsafe.Pointer) InterpolationControlSource {
	return gobject.UnsafeObjectFromGlibFull(c).(InterpolationControlSource)
}

// UnsafeInterpolationControlSourceFromGlibBorrow is used to convert raw GstInterpolationControlSource pointers to go without touching any references. This is used by the bindings internally.
func UnsafeInterpolationControlSourceFromGlibBorrow(c unsafe.Pointer) InterpolationControlSource {
	return gobject.UnsafeObjectFromGlibBorrow(c).(InterpolationControlSource)
}

func (i *InterpolationControlSourceInstance) upcastToGstInterpolationControlSource() *InterpolationControlSourceInstance {
	return i
}

// UnsafeInterpolationControlSourceToGlibNone is used to convert the instance to it's C value GstInterpolationControlSource. This is used by the bindings internally.
func UnsafeInterpolationControlSourceToGlibNone(c InterpolationControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeInterpolationControlSourceToGlibFull is used to convert the instance to it's C value GstInterpolationControlSource, while removeing the finalizer. This is used by the bindings internally.
func UnsafeInterpolationControlSourceToGlibFull(c InterpolationControlSource) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewInterpolationControlSource wraps gst_interpolation_control_source_new
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#gst_interpolation_control_source_new
func NewInterpolationControlSource() gst.ControlSource {
	var cret *C.GstControlSource // return, full, converted

	cret = C.gst_interpolation_control_source_new()

	var goret gst.ControlSource

	goret = gst.UnsafeControlSourceFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// InterpolationControlSourceOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type InterpolationControlSourceOverrides[Instance InterpolationControlSource] struct {
	// TimedValueControlSourceOverrides allows you to override virtual methods from the parent class TimedValueControlSource
	TimedValueControlSourceOverrides[Instance]

}

// UnsafeApplyInterpolationControlSourceOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyInterpolationControlSourceOverrides[Instance InterpolationControlSource](gclass unsafe.Pointer, overrides InterpolationControlSourceOverrides[Instance]) {
	UnsafeApplyTimedValueControlSourceOverrides(gclass, overrides.TimedValueControlSourceOverrides)
}

// RegisterInterpolationControlSourceSubClass is used to register a go subclass of GstInterpolationControlSource. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterInterpolationControlSourceSubClass[InstanceT InterpolationControlSource](
		name string,
		classInit func(class *InterpolationControlSourceClass),
		constructor func() InstanceT,
		overrides InterpolationControlSourceOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeInterpolationControlSource,
		UnsafeInterpolationControlSourceClassFromGlibBorrow,
		UnsafeApplyInterpolationControlSourceOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapInterpolationControlSource(obj)
		},
		interfaceInits...,
	)
}

// ARGBControlBindingClass wraps GstARGBControlBindingClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstargbcontrolbinding.html#GstARGBControlBindingClass
// 
// ARGBControlBindingClass is the type struct for [ARGBControlBinding]
type ARGBControlBindingClass struct {
	*aRGBControlBindingClass
}

// aRGBControlBindingClass is the struct that's finalized
type aRGBControlBindingClass struct {
	native *C.GstARGBControlBindingClass
}

// UnsafeARGBControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (a *ARGBControlBindingClass) instance() *C.GstARGBControlBindingClass {
	if a == nil {
		return nil
	}
	return a.native
}

// UnsafeARGBControlBindingClassFromGlibBorrow is used to convert raw C.GstARGBControlBindingClass pointers to go. This is used by the bindings internally.
func UnsafeARGBControlBindingClassFromGlibBorrow(p unsafe.Pointer) *ARGBControlBindingClass {
	if p == nil {
		return nil
	}
	return &ARGBControlBindingClass{&aRGBControlBindingClass{(*C.GstARGBControlBindingClass)(p)}}
}

// UnsafeARGBControlBindingClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [ARGBControlBindingClass] is expected to work anymore.
func UnsafeARGBControlBindingClassFree(a *ARGBControlBindingClass) {
	C.free(unsafe.Pointer(a.native))
	runtime.SetFinalizer(a.aRGBControlBindingClass, nil)
}

// UnsafeARGBControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeARGBControlBindingClassToGlibNone(a *ARGBControlBindingClass) unsafe.Pointer {
	if a == nil {
		return nil
	}
	return unsafe.Pointer(a.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (a *ARGBControlBindingClass) ParentClass() *gst.ControlBindingClass {
	parent := gst.UnsafeControlBindingClassFromGlibBorrow(UnsafeARGBControlBindingClassToGlibNone(a))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *ARGBControlBindingClass) {}, a)
	return parent
}

// ControlPoint wraps GstControlPoint
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#GstControlPoint
type ControlPoint struct {
	*controlPoint
}

// controlPoint is the struct that's finalized
type controlPoint struct {
	native *C.GstControlPoint
}

// UnsafeControlPointToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (c *ControlPoint) instance() *C.GstControlPoint {
	if c == nil {
		return nil
	}
	return c.native
}

var _ gobject.GoValueInitializer = (*ControlPoint)(nil)

func marshalControlPoint(p unsafe.Pointer) (interface{}, error) {
	b := gobject.ValueFromNative(p).Boxed()
	return UnsafeControlPointFromGlibNone(b), nil
}

func (r *ControlPoint) GoValueType() gobject.Type {
	return TypeControlPoint
}

func (r *ControlPoint) SetGoValue(v *gobject.Value) {
	v.SetBoxed(unsafe.Pointer(r.instance()))
}

// UnsafeControlPointFromGlibBorrow is used to convert raw C.GstControlPoint pointers to go. This is used by the bindings internally.
func UnsafeControlPointFromGlibBorrow(p unsafe.Pointer) *ControlPoint {
	if p == nil {
		return nil
	}
	return &ControlPoint{&controlPoint{(*C.GstControlPoint)(p)}}
}

// UnsafeControlPointFromGlibNone is used to convert raw C.GstControlPoint pointers to go without transferring ownership. This is used by the bindings internally.
func UnsafeControlPointFromGlibNone(p unsafe.Pointer) *ControlPoint {
	wrapped := UnsafeControlPointFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}

	return wrapped.Copy() // create an owned copy

}

// UnsafeControlPointFromGlibFull is used to convert raw C.GstControlPoint pointers to go while taking ownership. This is used by the bindings internally.
func UnsafeControlPointFromGlibFull(p unsafe.Pointer) *ControlPoint {
	wrapped := UnsafeControlPointFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}
	runtime.SetFinalizer(
		wrapped.controlPoint,
		func (intern *controlPoint) {
			C.gst_control_point_free(intern.native)
		},
	)
	return wrapped
}

// UnsafeControlPointFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [ControlPoint] is expected to work anymore.
func UnsafeControlPointFree(c *ControlPoint) {
	C.gst_control_point_free(c.native)
	runtime.SetFinalizer(c.controlPoint, nil)
}

// UnsafeControlPointToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeControlPointToGlibNone(c *ControlPoint) unsafe.Pointer {
	if c == nil {
		return nil
	}
	return unsafe.Pointer(c.native)
}

// UnsafeControlPointToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeControlPointToGlibFull(c *ControlPoint) unsafe.Pointer {
	if c == nil {
		return nil
	}
	runtime.SetFinalizer(c.controlPoint, nil)
	_p := unsafe.Pointer(c.native)
	c.native = nil // ControlPoint is invalid from here on
	return _p
}

// Copy wraps gst_control_point_copy
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#gst_control_point_copy
func (cp *ControlPoint) Copy() *ControlPoint {
	var carg0 *C.GstControlPoint // in, none, converted
	var cret  *C.GstControlPoint // return, full, converted

	carg0 = (*C.GstControlPoint)(UnsafeControlPointToGlibNone(cp))

	cret = C.gst_control_point_copy(carg0)
	runtime.KeepAlive(cp)

	var goret *ControlPoint

	goret = UnsafeControlPointFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// DirectControlBindingClass wraps GstDirectControlBindingClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstdirectcontrolbinding.html#GstDirectControlBindingClass
// 
// DirectControlBindingClass is the type struct for [DirectControlBinding]
type DirectControlBindingClass struct {
	*directControlBindingClass
}

// directControlBindingClass is the struct that's finalized
type directControlBindingClass struct {
	native *C.GstDirectControlBindingClass
}

// UnsafeDirectControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (d *DirectControlBindingClass) instance() *C.GstDirectControlBindingClass {
	if d == nil {
		return nil
	}
	return d.native
}

// UnsafeDirectControlBindingClassFromGlibBorrow is used to convert raw C.GstDirectControlBindingClass pointers to go. This is used by the bindings internally.
func UnsafeDirectControlBindingClassFromGlibBorrow(p unsafe.Pointer) *DirectControlBindingClass {
	if p == nil {
		return nil
	}
	return &DirectControlBindingClass{&directControlBindingClass{(*C.GstDirectControlBindingClass)(p)}}
}

// UnsafeDirectControlBindingClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [DirectControlBindingClass] is expected to work anymore.
func UnsafeDirectControlBindingClassFree(d *DirectControlBindingClass) {
	C.free(unsafe.Pointer(d.native))
	runtime.SetFinalizer(d.directControlBindingClass, nil)
}

// UnsafeDirectControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeDirectControlBindingClassToGlibNone(d *DirectControlBindingClass) unsafe.Pointer {
	if d == nil {
		return nil
	}
	return unsafe.Pointer(d.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (d *DirectControlBindingClass) ParentClass() *gst.ControlBindingClass {
	parent := gst.UnsafeControlBindingClassFromGlibBorrow(UnsafeDirectControlBindingClassToGlibNone(d))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *DirectControlBindingClass) {}, d)
	return parent
}

// InterpolationControlSourceClass wraps GstInterpolationControlSourceClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstinterpolationcontrolsource.html#GstInterpolationControlSourceClass
// 
// InterpolationControlSourceClass is the type struct for [InterpolationControlSource]
type InterpolationControlSourceClass struct {
	*interpolationControlSourceClass
}

// interpolationControlSourceClass is the struct that's finalized
type interpolationControlSourceClass struct {
	native *C.GstInterpolationControlSourceClass
}

// UnsafeInterpolationControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (i *InterpolationControlSourceClass) instance() *C.GstInterpolationControlSourceClass {
	if i == nil {
		return nil
	}
	return i.native
}

// UnsafeInterpolationControlSourceClassFromGlibBorrow is used to convert raw C.GstInterpolationControlSourceClass pointers to go. This is used by the bindings internally.
func UnsafeInterpolationControlSourceClassFromGlibBorrow(p unsafe.Pointer) *InterpolationControlSourceClass {
	if p == nil {
		return nil
	}
	return &InterpolationControlSourceClass{&interpolationControlSourceClass{(*C.GstInterpolationControlSourceClass)(p)}}
}

// UnsafeInterpolationControlSourceClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [InterpolationControlSourceClass] is expected to work anymore.
func UnsafeInterpolationControlSourceClassFree(i *InterpolationControlSourceClass) {
	C.free(unsafe.Pointer(i.native))
	runtime.SetFinalizer(i.interpolationControlSourceClass, nil)
}

// UnsafeInterpolationControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeInterpolationControlSourceClassToGlibNone(i *InterpolationControlSourceClass) unsafe.Pointer {
	if i == nil {
		return nil
	}
	return unsafe.Pointer(i.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (i *InterpolationControlSourceClass) ParentClass() *TimedValueControlSourceClass {
	parent := UnsafeTimedValueControlSourceClassFromGlibBorrow(UnsafeInterpolationControlSourceClassToGlibNone(i))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *InterpolationControlSourceClass) {}, i)
	return parent
}

// LFOControlSourceClass wraps GstLFOControlSourceClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstlfocontrolsource.html#GstLFOControlSourceClass
// 
// LFOControlSourceClass is the type struct for [LFOControlSource]
type LFOControlSourceClass struct {
	*lFOControlSourceClass
}

// lFOControlSourceClass is the struct that's finalized
type lFOControlSourceClass struct {
	native *C.GstLFOControlSourceClass
}

// UnsafeLFOControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (l *LFOControlSourceClass) instance() *C.GstLFOControlSourceClass {
	if l == nil {
		return nil
	}
	return l.native
}

// UnsafeLFOControlSourceClassFromGlibBorrow is used to convert raw C.GstLFOControlSourceClass pointers to go. This is used by the bindings internally.
func UnsafeLFOControlSourceClassFromGlibBorrow(p unsafe.Pointer) *LFOControlSourceClass {
	if p == nil {
		return nil
	}
	return &LFOControlSourceClass{&lFOControlSourceClass{(*C.GstLFOControlSourceClass)(p)}}
}

// UnsafeLFOControlSourceClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [LFOControlSourceClass] is expected to work anymore.
func UnsafeLFOControlSourceClassFree(l *LFOControlSourceClass) {
	C.free(unsafe.Pointer(l.native))
	runtime.SetFinalizer(l.lFOControlSourceClass, nil)
}

// UnsafeLFOControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeLFOControlSourceClassToGlibNone(l *LFOControlSourceClass) unsafe.Pointer {
	if l == nil {
		return nil
	}
	return unsafe.Pointer(l.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (l *LFOControlSourceClass) ParentClass() *gst.ControlSourceClass {
	parent := gst.UnsafeControlSourceClassFromGlibBorrow(UnsafeLFOControlSourceClassToGlibNone(l))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *LFOControlSourceClass) {}, l)
	return parent
}

// ProxyControlBindingClass wraps GstProxyControlBindingClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gstproxycontrolbinding.html#GstProxyControlBindingClass
// 
// ProxyControlBindingClass is the type struct for [ProxyControlBinding]
type ProxyControlBindingClass struct {
	*proxyControlBindingClass
}

// proxyControlBindingClass is the struct that's finalized
type proxyControlBindingClass struct {
	native *C.GstProxyControlBindingClass
}

// UnsafeProxyControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (p *ProxyControlBindingClass) instance() *C.GstProxyControlBindingClass {
	if p == nil {
		return nil
	}
	return p.native
}

// UnsafeProxyControlBindingClassFromGlibBorrow is used to convert raw C.GstProxyControlBindingClass pointers to go. This is used by the bindings internally.
func UnsafeProxyControlBindingClassFromGlibBorrow(p unsafe.Pointer) *ProxyControlBindingClass {
	if p == nil {
		return nil
	}
	return &ProxyControlBindingClass{&proxyControlBindingClass{(*C.GstProxyControlBindingClass)(p)}}
}

// UnsafeProxyControlBindingClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [ProxyControlBindingClass] is expected to work anymore.
func UnsafeProxyControlBindingClassFree(p *ProxyControlBindingClass) {
	C.free(unsafe.Pointer(p.native))
	runtime.SetFinalizer(p.proxyControlBindingClass, nil)
}

// UnsafeProxyControlBindingClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeProxyControlBindingClassToGlibNone(p *ProxyControlBindingClass) unsafe.Pointer {
	if p == nil {
		return nil
	}
	return unsafe.Pointer(p.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (p *ProxyControlBindingClass) ParentClass() *gst.ControlBindingClass {
	parent := gst.UnsafeControlBindingClassFromGlibBorrow(UnsafeProxyControlBindingClassToGlibNone(p))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *ProxyControlBindingClass) {}, p)
	return parent
}

// TimedValueControlSourceClass wraps GstTimedValueControlSourceClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttimedvaluecontrolsource.html#GstTimedValueControlSourceClass
// 
// TimedValueControlSourceClass is the type struct for [TimedValueControlSource]
type TimedValueControlSourceClass struct {
	*timedValueControlSourceClass
}

// timedValueControlSourceClass is the struct that's finalized
type timedValueControlSourceClass struct {
	native *C.GstTimedValueControlSourceClass
}

// UnsafeTimedValueControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (t *TimedValueControlSourceClass) instance() *C.GstTimedValueControlSourceClass {
	if t == nil {
		return nil
	}
	return t.native
}

// UnsafeTimedValueControlSourceClassFromGlibBorrow is used to convert raw C.GstTimedValueControlSourceClass pointers to go. This is used by the bindings internally.
func UnsafeTimedValueControlSourceClassFromGlibBorrow(p unsafe.Pointer) *TimedValueControlSourceClass {
	if p == nil {
		return nil
	}
	return &TimedValueControlSourceClass{&timedValueControlSourceClass{(*C.GstTimedValueControlSourceClass)(p)}}
}

// UnsafeTimedValueControlSourceClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [TimedValueControlSourceClass] is expected to work anymore.
func UnsafeTimedValueControlSourceClassFree(t *TimedValueControlSourceClass) {
	C.free(unsafe.Pointer(t.native))
	runtime.SetFinalizer(t.timedValueControlSourceClass, nil)
}

// UnsafeTimedValueControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeTimedValueControlSourceClassToGlibNone(t *TimedValueControlSourceClass) unsafe.Pointer {
	if t == nil {
		return nil
	}
	return unsafe.Pointer(t.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (t *TimedValueControlSourceClass) ParentClass() *gst.ControlSourceClass {
	parent := gst.UnsafeControlSourceClassFromGlibBorrow(UnsafeTimedValueControlSourceClassToGlibNone(t))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *TimedValueControlSourceClass) {}, t)
	return parent
}

// TriggerControlSourceClass wraps GstTriggerControlSourceClass
// 
// see also https://gstreamer.freedesktop.org/documentation/controller/gsttriggercontrolsource.html#GstTriggerControlSourceClass
// 
// TriggerControlSourceClass is the type struct for [TriggerControlSource]
type TriggerControlSourceClass struct {
	*triggerControlSourceClass
}

// triggerControlSourceClass is the struct that's finalized
type triggerControlSourceClass struct {
	native *C.GstTriggerControlSourceClass
}

// UnsafeTriggerControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (t *TriggerControlSourceClass) instance() *C.GstTriggerControlSourceClass {
	if t == nil {
		return nil
	}
	return t.native
}

// UnsafeTriggerControlSourceClassFromGlibBorrow is used to convert raw C.GstTriggerControlSourceClass pointers to go. This is used by the bindings internally.
func UnsafeTriggerControlSourceClassFromGlibBorrow(p unsafe.Pointer) *TriggerControlSourceClass {
	if p == nil {
		return nil
	}
	return &TriggerControlSourceClass{&triggerControlSourceClass{(*C.GstTriggerControlSourceClass)(p)}}
}

// UnsafeTriggerControlSourceClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [TriggerControlSourceClass] is expected to work anymore.
func UnsafeTriggerControlSourceClassFree(t *TriggerControlSourceClass) {
	C.free(unsafe.Pointer(t.native))
	runtime.SetFinalizer(t.triggerControlSourceClass, nil)
}

// UnsafeTriggerControlSourceClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeTriggerControlSourceClassToGlibNone(t *TriggerControlSourceClass) unsafe.Pointer {
	if t == nil {
		return nil
	}
	return unsafe.Pointer(t.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (t *TriggerControlSourceClass) ParentClass() *TimedValueControlSourceClass {
	parent := UnsafeTimedValueControlSourceClassFromGlibBorrow(UnsafeTriggerControlSourceClassToGlibNone(t))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *TriggerControlSourceClass) {}, t)
	return parent
}

