// Code generated by girgen for GstNet-1. DO NOT EDIT.

package gstnet

import (
	"log"
	"runtime"
	"unsafe"

	"github.com/go-gst/go-glib/pkg/core/userdata"
	"github.com/go-gst/go-glib/pkg/gio/v2"
	"github.com/go-gst/go-glib/pkg/glib/v2"
	"github.com/go-gst/go-glib/pkg/gobject/v2"
	"github.com/go-gst/go-gst/pkg/gst"
)

// #cgo pkg-config: gstreamer-net-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gst/net/net.h>
// extern gboolean _goglib_gstnet1_PtpStatisticsCallback(guint8, const GstStructure*, gpointer);
// extern void destroyUserdata(gpointer);
import "C"

// GType values.
var (
	TypeNetClientClock  = gobject.Type(C.gst_net_client_clock_get_type())
	TypeNetTimeProvider = gobject.Type(C.gst_net_time_provider_get_type())
	TypeNtpClock        = gobject.Type(C.gst_ntp_clock_get_type())
	TypePtpClock        = gobject.Type(C.gst_ptp_clock_get_type())
	TypeNetTimePacket   = gobject.Type(C.gst_net_time_packet_get_type())
)

func init() {
	gobject.RegisterGValueMarshalers([]gobject.TypeMarshaler{
		gobject.TypeMarshaler{T: TypeNetClientClock, F: marshalNetClientClockInstance},
		gobject.TypeMarshaler{T: TypeNetTimeProvider, F: marshalNetTimeProviderInstance},
		gobject.TypeMarshaler{T: TypeNtpClock, F: marshalNtpClockInstance},
		gobject.TypeMarshaler{T: TypePtpClock, F: marshalPtpClockInstance},
		gobject.TypeMarshaler{T: TypeNetTimePacket, F: marshalNetTimePacket},
	})
}

// NET_TIME_PACKET_SIZE wraps GST_NET_TIME_PACKET_SIZE
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#GST_NET_TIME_PACKET_SIZE
const NET_TIME_PACKET_SIZE = 16
// PTP_CLOCK_ID_NONE wraps GST_PTP_CLOCK_ID_NONE
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstptpclock.html#GST_PTP_CLOCK_ID_NONE
const PTP_CLOCK_ID_NONE = 18446744073709551615
// PtpStatisticsCallback wraps GstPtpStatisticsCallback
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstptpclock.html#GstPtpStatisticsCallback
type PtpStatisticsCallback func(domain uint8, stats *gst.Structure) (goret bool)

// BufferAddNetAddressMeta wraps gst_buffer_add_net_address_meta
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func BufferAddNetAddressMeta(buffer *gst.Buffer, addr gio.SocketAddress) *NetAddressMeta {
	var carg1 *C.GstBuffer         // in, none, converted
	var carg2 *C.GSocketAddress    // in, none, converted
	var cret  *C.GstNetAddressMeta // return, none, converted

	carg1 = (*C.GstBuffer)(gst.UnsafeBufferToGlibNone(buffer))
	carg2 = (*C.GSocketAddress)(gio.UnsafeSocketAddressToGlibNone(addr))

	cret = C.gst_buffer_add_net_address_meta(carg1, carg2)
	runtime.KeepAlive(buffer)
	runtime.KeepAlive(addr)

	var goret *NetAddressMeta

	goret = UnsafeNetAddressMetaFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// BufferAddNetControlMessageMeta wraps gst_buffer_add_net_control_message_meta
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func BufferAddNetControlMessageMeta(buffer *gst.Buffer, message gio.SocketControlMessage) *NetControlMessageMeta {
	var carg1 *C.GstBuffer                // in, none, converted
	var carg2 *C.GSocketControlMessage    // in, none, converted
	var cret  *C.GstNetControlMessageMeta // return, none, converted

	carg1 = (*C.GstBuffer)(gst.UnsafeBufferToGlibNone(buffer))
	carg2 = (*C.GSocketControlMessage)(gio.UnsafeSocketControlMessageToGlibNone(message))

	cret = C.gst_buffer_add_net_control_message_meta(carg1, carg2)
	runtime.KeepAlive(buffer)
	runtime.KeepAlive(message)

	var goret *NetControlMessageMeta

	goret = UnsafeNetControlMessageMetaFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// BufferGetNetAddressMeta wraps gst_buffer_get_net_address_meta
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func BufferGetNetAddressMeta(buffer *gst.Buffer) *NetAddressMeta {
	var carg1 *C.GstBuffer         // in, none, converted
	var cret  *C.GstNetAddressMeta // return, none, converted, nullable

	carg1 = (*C.GstBuffer)(gst.UnsafeBufferToGlibNone(buffer))

	cret = C.gst_buffer_get_net_address_meta(carg1)
	runtime.KeepAlive(buffer)

	var goret *NetAddressMeta

	if cret != nil {
		goret = UnsafeNetAddressMetaFromGlibNone(unsafe.Pointer(cret))
	}

	return goret
}

// NetAddressMetaAPIGetType wraps gst_net_address_meta_api_get_type
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func NetAddressMetaAPIGetType() gobject.Type {
	var cret C.GType // return, none, casted, alias

	cret = C.gst_net_address_meta_api_get_type()

	var goret gobject.Type

	goret = gobject.Type(cret)

	return goret
}

// NetControlMessageMetaAPIGetType wraps gst_net_control_message_meta_api_get_type
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func NetControlMessageMetaAPIGetType() gobject.Type {
	var cret C.GType // return, none, casted, alias

	cret = C.gst_net_control_message_meta_api_get_type()

	var goret gobject.Type

	goret = gobject.Type(cret)

	return goret
}

// NetUtilsSetSocketTos wraps gst_net_utils_set_socket_tos
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func NetUtilsSetSocketTos(socket gio.Socket, qosDscp int32) bool {
	var carg1 *C.GSocket // in, none, converted
	var carg2 C.gint     // in, none, casted
	var cret  C.gboolean // return

	carg1 = (*C.GSocket)(gio.UnsafeSocketToGlibNone(socket))
	carg2 = C.gint(qosDscp)

	cret = C.gst_net_utils_set_socket_tos(carg1, carg2)
	runtime.KeepAlive(socket)
	runtime.KeepAlive(qosDscp)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PtpDeinit wraps gst_ptp_deinit
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpDeinit() {

	C.gst_ptp_deinit()
}

// PtpInit wraps gst_ptp_init
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpInit(clockId uint64, interfaces []string) bool {
	var carg1 C.guint64  // in, none, casted
	var carg2 **C.gchar  // in, transfer: none, C Pointers: 2, Name: array[utf8], nullable, array (inner gchar* (*typesystem.StringPrimitive), zero-terminated)
	var cret  C.gboolean // return

	carg1 = C.guint64(clockId)
	_ = interfaces
	_ = carg2
	panic("unimplemented conversion of []string (gchar**) because of unimplemented: inner pointers in array")

	cret = C.gst_ptp_init(carg1, carg2)
	runtime.KeepAlive(clockId)
	runtime.KeepAlive(interfaces)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PtpInitFull wraps gst_ptp_init_full
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpInitFull(config *gst.Structure) bool {
	var carg1 *C.GstStructure // in, none, converted
	var cret  C.gboolean      // return

	carg1 = (*C.GstStructure)(gst.UnsafeStructureToGlibNone(config))

	cret = C.gst_ptp_init_full(carg1)
	runtime.KeepAlive(config)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PtpIsInitialized wraps gst_ptp_is_initialized
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpIsInitialized() bool {
	var cret C.gboolean // return

	cret = C.gst_ptp_is_initialized()

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PtpIsSupported wraps gst_ptp_is_supported
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpIsSupported() bool {
	var cret C.gboolean // return

	cret = C.gst_ptp_is_supported()

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PtpStatisticsCallbackAdd wraps gst_ptp_statistics_callback_add
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpStatisticsCallbackAdd(callback PtpStatisticsCallback) uint32 {
	var carg1 C.GstPtpStatisticsCallback // callback, scope: notified, closure: carg2, destroy: carg3
	var carg2 C.gpointer                 // implicit
	var carg3 C.GDestroyNotify           // implicit
	var cret  C.gulong                   // return, none, casted

	carg1 = (*[0]byte)(C._goglib_gstnet1_PtpStatisticsCallback)
	carg2 = C.gpointer(userdata.Register(callback))
	carg3 = (C.GDestroyNotify)((*[0]byte)(C.destroyUserdata))

	cret = C.gst_ptp_statistics_callback_add(carg1, carg2, carg3)
	runtime.KeepAlive(callback)

	var goret uint32

	goret = uint32(cret)

	return goret
}

// PtpStatisticsCallbackRemove wraps gst_ptp_statistics_callback_remove
// 
// see also https://gstreamer.freedesktop.org/documentation/net
func PtpStatisticsCallbackRemove(id uint32) {
	var carg1 C.gulong // in, none, casted

	carg1 = C.gulong(id)

	C.gst_ptp_statistics_callback_remove(carg1)
	runtime.KeepAlive(id)
}

// NetClientClockInstance is the instance type used by all types extending GstNetClientClock. It is used internally by the bindings. Users should use the interface [NetClientClock] instead.
type NetClientClockInstance struct {
	_ [0]func() // equal guard
	gst.SystemClockInstance
}

var _ NetClientClock = (*NetClientClockInstance)(nil)

// NetClientClock wraps GstNetClientClock
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#GstNetClientClock
type NetClientClock interface {
	gst.SystemClock
	upcastToGstNetClientClock() *NetClientClockInstance

	// chain up virtual methods:
}

func unsafeWrapNetClientClock(base *gobject.ObjectInstance) *NetClientClockInstance {
	return &NetClientClockInstance{
		SystemClockInstance: gst.SystemClockInstance{
			ClockInstance: gst.ClockInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeNetClientClock,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNetClientClock(inst)
		},
	)
}

func marshalNetClientClockInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeNetClientClockFromGlibNone is used to convert raw GstNetClientClock pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeNetClientClockFromGlibNone(c unsafe.Pointer) NetClientClock {
	return gobject.UnsafeObjectFromGlibNone(c).(NetClientClock)
}

// UnsafeNetClientClockFromGlibFull is used to convert raw GstNetClientClock pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeNetClientClockFromGlibFull(c unsafe.Pointer) NetClientClock {
	return gobject.UnsafeObjectFromGlibFull(c).(NetClientClock)
}

// UnsafeNetClientClockFromGlibBorrow is used to convert raw GstNetClientClock pointers to go without touching any references. This is used by the bindings internally.
func UnsafeNetClientClockFromGlibBorrow(c unsafe.Pointer) NetClientClock {
	return gobject.UnsafeObjectFromGlibBorrow(c).(NetClientClock)
}

func (n *NetClientClockInstance) upcastToGstNetClientClock() *NetClientClockInstance {
	return n
}

// UnsafeNetClientClockToGlibNone is used to convert the instance to it's C value GstNetClientClock. This is used by the bindings internally.
func UnsafeNetClientClockToGlibNone(c NetClientClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeNetClientClockToGlibFull is used to convert the instance to it's C value GstNetClientClock, while removeing the finalizer. This is used by the bindings internally.
func UnsafeNetClientClockToGlibFull(c NetClientClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewNetClientClock wraps gst_net_client_clock_new
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#gst_net_client_clock_new
func NewNetClientClock(name string, remoteAddress string, remotePort int32, baseTime gst.ClockTime) gst.Clock {
	var carg1 *C.gchar       // in, none, string, nullable-string
	var carg2 *C.gchar       // in, none, string
	var carg3 C.gint         // in, none, casted
	var carg4 C.GstClockTime // in, none, casted, alias
	var cret  *C.GstClock    // return, full, converted

	if name != "" {
		carg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
		defer C.free(unsafe.Pointer(carg1))
	}
	carg2 = (*C.gchar)(unsafe.Pointer(C.CString(remoteAddress)))
	defer C.free(unsafe.Pointer(carg2))
	carg3 = C.gint(remotePort)
	carg4 = C.GstClockTime(baseTime)

	cret = C.gst_net_client_clock_new(carg1, carg2, carg3, carg4)
	runtime.KeepAlive(name)
	runtime.KeepAlive(remoteAddress)
	runtime.KeepAlive(remotePort)
	runtime.KeepAlive(baseTime)

	var goret gst.Clock

	goret = gst.UnsafeClockFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// NetClientClockOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type NetClientClockOverrides[Instance NetClientClock] struct {
	// gst.SystemClockOverrides allows you to override virtual methods from the parent class gst.SystemClock
	gst.SystemClockOverrides[Instance]

}

// UnsafeApplyNetClientClockOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyNetClientClockOverrides[Instance NetClientClock](gclass unsafe.Pointer, overrides NetClientClockOverrides[Instance]) {
	gst.UnsafeApplySystemClockOverrides(gclass, overrides.SystemClockOverrides)
}

// RegisterNetClientClockSubClass is used to register a go subclass of GstNetClientClock. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterNetClientClockSubClass[InstanceT NetClientClock](
		name string,
		classInit func(class *NetClientClockClass),
		constructor func() InstanceT,
		overrides NetClientClockOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeNetClientClock,
		UnsafeNetClientClockClassFromGlibBorrow,
		UnsafeApplyNetClientClockOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNetClientClock(obj)
		},
		interfaceInits...,
	)
}

// NetTimeProviderInstance is the instance type used by all types extending GstNetTimeProvider. It is used internally by the bindings. Users should use the interface [NetTimeProvider] instead.
type NetTimeProviderInstance struct {
	_ [0]func() // equal guard
	gst.ObjectInstance
	// implemented interfaces:
	gio.InitableInstance
}

var _ NetTimeProvider = (*NetTimeProviderInstance)(nil)

// NetTimeProvider wraps GstNetTimeProvider
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimeprovider.html#GstNetTimeProvider
type NetTimeProvider interface {
	gst.Object
	gio.Initable
	upcastToGstNetTimeProvider() *NetTimeProviderInstance

	// chain up virtual methods:
}

func unsafeWrapNetTimeProvider(base *gobject.ObjectInstance) *NetTimeProviderInstance {
	return &NetTimeProviderInstance{
		ObjectInstance: gst.ObjectInstance{
			InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
				ObjectInstance: *base,
			},
		},
		InitableInstance: gio.InitableInstance{
			Instance: *base,
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeNetTimeProvider,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNetTimeProvider(inst)
		},
	)
}

func marshalNetTimeProviderInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeNetTimeProviderFromGlibNone is used to convert raw GstNetTimeProvider pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeNetTimeProviderFromGlibNone(c unsafe.Pointer) NetTimeProvider {
	return gobject.UnsafeObjectFromGlibNone(c).(NetTimeProvider)
}

// UnsafeNetTimeProviderFromGlibFull is used to convert raw GstNetTimeProvider pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeNetTimeProviderFromGlibFull(c unsafe.Pointer) NetTimeProvider {
	return gobject.UnsafeObjectFromGlibFull(c).(NetTimeProvider)
}

// UnsafeNetTimeProviderFromGlibBorrow is used to convert raw GstNetTimeProvider pointers to go without touching any references. This is used by the bindings internally.
func UnsafeNetTimeProviderFromGlibBorrow(c unsafe.Pointer) NetTimeProvider {
	return gobject.UnsafeObjectFromGlibBorrow(c).(NetTimeProvider)
}

func (n *NetTimeProviderInstance) upcastToGstNetTimeProvider() *NetTimeProviderInstance {
	return n
}

// UnsafeNetTimeProviderToGlibNone is used to convert the instance to it's C value GstNetTimeProvider. This is used by the bindings internally.
func UnsafeNetTimeProviderToGlibNone(c NetTimeProvider) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeNetTimeProviderToGlibFull is used to convert the instance to it's C value GstNetTimeProvider, while removeing the finalizer. This is used by the bindings internally.
func UnsafeNetTimeProviderToGlibFull(c NetTimeProvider) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewNetTimeProvider wraps gst_net_time_provider_new
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimeprovider.html#gst_net_time_provider_new
func NewNetTimeProvider(clock gst.Clock, address string, port int32) NetTimeProvider {
	var carg1 *C.GstClock           // in, none, converted
	var carg2 *C.gchar              // in, none, string, nullable-string
	var carg3 C.gint                // in, none, casted
	var cret  *C.GstNetTimeProvider // return, full, converted, nullable

	carg1 = (*C.GstClock)(gst.UnsafeClockToGlibNone(clock))
	if address != "" {
		carg2 = (*C.gchar)(unsafe.Pointer(C.CString(address)))
		defer C.free(unsafe.Pointer(carg2))
	}
	carg3 = C.gint(port)

	cret = C.gst_net_time_provider_new(carg1, carg2, carg3)
	runtime.KeepAlive(clock)
	runtime.KeepAlive(address)
	runtime.KeepAlive(port)

	var goret NetTimeProvider

	if cret != nil {
		goret = UnsafeNetTimeProviderFromGlibFull(unsafe.Pointer(cret))
	}

	return goret
}

// NetTimeProviderOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type NetTimeProviderOverrides[Instance NetTimeProvider] struct {
	// gst.ObjectOverrides allows you to override virtual methods from the parent class gst.Object
	gst.ObjectOverrides[Instance]

}

// UnsafeApplyNetTimeProviderOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyNetTimeProviderOverrides[Instance NetTimeProvider](gclass unsafe.Pointer, overrides NetTimeProviderOverrides[Instance]) {
	gst.UnsafeApplyObjectOverrides(gclass, overrides.ObjectOverrides)
}

// RegisterNetTimeProviderSubClass is used to register a go subclass of GstNetTimeProvider. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterNetTimeProviderSubClass[InstanceT NetTimeProvider](
		name string,
		classInit func(class *NetTimeProviderClass),
		constructor func() InstanceT,
		overrides NetTimeProviderOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeNetTimeProvider,
		UnsafeNetTimeProviderClassFromGlibBorrow,
		UnsafeApplyNetTimeProviderOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNetTimeProvider(obj)
		},
		interfaceInits...,
	)
}

// NtpClockInstance is the instance type used by all types extending GstNtpClock. It is used internally by the bindings. Users should use the interface [NtpClock] instead.
type NtpClockInstance struct {
	_ [0]func() // equal guard
	NetClientClockInstance
}

var _ NtpClock = (*NtpClockInstance)(nil)

// NtpClock wraps GstNtpClock
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#GstNtpClock
type NtpClock interface {
	NetClientClock
	upcastToGstNtpClock() *NtpClockInstance

	// chain up virtual methods:
}

func unsafeWrapNtpClock(base *gobject.ObjectInstance) *NtpClockInstance {
	return &NtpClockInstance{
		NetClientClockInstance: NetClientClockInstance{
			SystemClockInstance: gst.SystemClockInstance{
				ClockInstance: gst.ClockInstance{
					ObjectInstance: gst.ObjectInstance{
						InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
							ObjectInstance: *base,
						},
					},
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypeNtpClock,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNtpClock(inst)
		},
	)
}

func marshalNtpClockInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafeNtpClockFromGlibNone is used to convert raw GstNtpClock pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeNtpClockFromGlibNone(c unsafe.Pointer) NtpClock {
	return gobject.UnsafeObjectFromGlibNone(c).(NtpClock)
}

// UnsafeNtpClockFromGlibFull is used to convert raw GstNtpClock pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeNtpClockFromGlibFull(c unsafe.Pointer) NtpClock {
	return gobject.UnsafeObjectFromGlibFull(c).(NtpClock)
}

// UnsafeNtpClockFromGlibBorrow is used to convert raw GstNtpClock pointers to go without touching any references. This is used by the bindings internally.
func UnsafeNtpClockFromGlibBorrow(c unsafe.Pointer) NtpClock {
	return gobject.UnsafeObjectFromGlibBorrow(c).(NtpClock)
}

func (n *NtpClockInstance) upcastToGstNtpClock() *NtpClockInstance {
	return n
}

// UnsafeNtpClockToGlibNone is used to convert the instance to it's C value GstNtpClock. This is used by the bindings internally.
func UnsafeNtpClockToGlibNone(c NtpClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeNtpClockToGlibFull is used to convert the instance to it's C value GstNtpClock, while removeing the finalizer. This is used by the bindings internally.
func UnsafeNtpClockToGlibFull(c NtpClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewNtpClock wraps gst_ntp_clock_new
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#gst_ntp_clock_new
func NewNtpClock(name string, remoteAddress string, remotePort int32, baseTime gst.ClockTime) gst.Clock {
	var carg1 *C.gchar       // in, none, string, nullable-string
	var carg2 *C.gchar       // in, none, string
	var carg3 C.gint         // in, none, casted
	var carg4 C.GstClockTime // in, none, casted, alias
	var cret  *C.GstClock    // return, full, converted

	if name != "" {
		carg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
		defer C.free(unsafe.Pointer(carg1))
	}
	carg2 = (*C.gchar)(unsafe.Pointer(C.CString(remoteAddress)))
	defer C.free(unsafe.Pointer(carg2))
	carg3 = C.gint(remotePort)
	carg4 = C.GstClockTime(baseTime)

	cret = C.gst_ntp_clock_new(carg1, carg2, carg3, carg4)
	runtime.KeepAlive(name)
	runtime.KeepAlive(remoteAddress)
	runtime.KeepAlive(remotePort)
	runtime.KeepAlive(baseTime)

	var goret gst.Clock

	goret = gst.UnsafeClockFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// NtpClockOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type NtpClockOverrides[Instance NtpClock] struct {
	// NetClientClockOverrides allows you to override virtual methods from the parent class NetClientClock
	NetClientClockOverrides[Instance]

}

// UnsafeApplyNtpClockOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyNtpClockOverrides[Instance NtpClock](gclass unsafe.Pointer, overrides NtpClockOverrides[Instance]) {
	UnsafeApplyNetClientClockOverrides(gclass, overrides.NetClientClockOverrides)
}

// RegisterNtpClockSubClass is used to register a go subclass of GstNtpClock. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterNtpClockSubClass[InstanceT NtpClock](
		name string,
		classInit func(class *NtpClockClass),
		constructor func() InstanceT,
		overrides NtpClockOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypeNtpClock,
		UnsafeNtpClockClassFromGlibBorrow,
		UnsafeApplyNtpClockOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapNtpClock(obj)
		},
		interfaceInits...,
	)
}

// PtpClockInstance is the instance type used by all types extending GstPtpClock. It is used internally by the bindings. Users should use the interface [PtpClock] instead.
type PtpClockInstance struct {
	_ [0]func() // equal guard
	gst.SystemClockInstance
}

var _ PtpClock = (*PtpClockInstance)(nil)

// PtpClock wraps GstPtpClock
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstptpclock.html#GstPtpClock
type PtpClock interface {
	gst.SystemClock
	upcastToGstPtpClock() *PtpClockInstance

	// chain up virtual methods:
}

func unsafeWrapPtpClock(base *gobject.ObjectInstance) *PtpClockInstance {
	return &PtpClockInstance{
		SystemClockInstance: gst.SystemClockInstance{
			ClockInstance: gst.ClockInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
	}
}

func init() {
	gobject.RegisterObjectCasting(
		TypePtpClock,
		func (inst *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapPtpClock(inst)
		},
	)
}

func marshalPtpClockInstance(p unsafe.Pointer) (any, error) {
	return gobject.ValueFromNative(p).Object(), nil
}

// UnsafePtpClockFromGlibNone is used to convert raw GstPtpClock pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafePtpClockFromGlibNone(c unsafe.Pointer) PtpClock {
	return gobject.UnsafeObjectFromGlibNone(c).(PtpClock)
}

// UnsafePtpClockFromGlibFull is used to convert raw GstPtpClock pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafePtpClockFromGlibFull(c unsafe.Pointer) PtpClock {
	return gobject.UnsafeObjectFromGlibFull(c).(PtpClock)
}

// UnsafePtpClockFromGlibBorrow is used to convert raw GstPtpClock pointers to go without touching any references. This is used by the bindings internally.
func UnsafePtpClockFromGlibBorrow(c unsafe.Pointer) PtpClock {
	return gobject.UnsafeObjectFromGlibBorrow(c).(PtpClock)
}

func (p *PtpClockInstance) upcastToGstPtpClock() *PtpClockInstance {
	return p
}

// UnsafePtpClockToGlibNone is used to convert the instance to it's C value GstPtpClock. This is used by the bindings internally.
func UnsafePtpClockToGlibNone(c PtpClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafePtpClockToGlibFull is used to convert the instance to it's C value GstPtpClock, while removeing the finalizer. This is used by the bindings internally.
func UnsafePtpClockToGlibFull(c PtpClock) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// NewPtpClock wraps gst_ptp_clock_new
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstptpclock.html#gst_ptp_clock_new
func NewPtpClock(name string, domain uint) gst.Clock {
	var carg1 *C.gchar    // in, none, string, nullable-string
	var carg2 C.guint     // in, none, casted
	var cret  *C.GstClock // return, full, converted, nullable

	if name != "" {
		carg1 = (*C.gchar)(unsafe.Pointer(C.CString(name)))
		defer C.free(unsafe.Pointer(carg1))
	}
	carg2 = C.guint(domain)

	cret = C.gst_ptp_clock_new(carg1, carg2)
	runtime.KeepAlive(name)
	runtime.KeepAlive(domain)

	var goret gst.Clock

	if cret != nil {
		goret = gst.UnsafeClockFromGlibFull(unsafe.Pointer(cret))
	}

	return goret
}

// PtpClockOverrides is the struct used to override the default implementation of virtual methods.
// it is generic over the extending instance type.
type PtpClockOverrides[Instance PtpClock] struct {
	// gst.SystemClockOverrides allows you to override virtual methods from the parent class gst.SystemClock
	gst.SystemClockOverrides[Instance]

}

// UnsafeApplyPtpClockOverrides applies the overrides to init the gclass by setting the trampoline functions.
// This is used by the bindings internally and only exported for visibility to other bindings code.
func UnsafeApplyPtpClockOverrides[Instance PtpClock](gclass unsafe.Pointer, overrides PtpClockOverrides[Instance]) {
	gst.UnsafeApplySystemClockOverrides(gclass, overrides.SystemClockOverrides)
}

// RegisterPtpClockSubClass is used to register a go subclass of GstPtpClock. For this to work safely please implement the
// virtual methods required by the implementation.
func RegisterPtpClockSubClass[InstanceT PtpClock](
		name string,
		classInit func(class *PtpClockClass),
		constructor func() InstanceT,
		overrides PtpClockOverrides[InstanceT],
		signals map[string]gobject.SignalDefinition,
		interfaceInits ...gobject.SubClassInterfaceInit[InstanceT],
) gobject.Type {
	return gobject.UnsafeRegisterSubClass(
		name,
		classInit,
		constructor,
		overrides,
		signals,
		TypePtpClock,
		UnsafePtpClockClassFromGlibBorrow,
		UnsafeApplyPtpClockOverrides,
		func (obj *gobject.ObjectInstance) gobject.Object {
			return unsafeWrapPtpClock(obj)
		},
		interfaceInits...,
	)
}

// NetAddressMeta wraps GstNetAddressMeta
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetaddressmeta.html#GstNetAddressMeta
type NetAddressMeta struct {
	*netAddressMeta
}

// netAddressMeta is the struct that's finalized
type netAddressMeta struct {
	native *C.GstNetAddressMeta
}

// UnsafeNetAddressMetaToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NetAddressMeta) instance() *C.GstNetAddressMeta {
	if n == nil {
		return nil
	}
	return n.native
}

// UnsafeNetAddressMetaFromGlibBorrow is used to convert raw C.GstNetAddressMeta pointers to go. This is used by the bindings internally.
func UnsafeNetAddressMetaFromGlibBorrow(p unsafe.Pointer) *NetAddressMeta {
	if p == nil {
		return nil
	}
	return &NetAddressMeta{&netAddressMeta{(*C.GstNetAddressMeta)(p)}}
}

// UnsafeNetAddressMetaFromGlibNone is used to convert raw C.GstNetAddressMeta pointers to go without transferring ownership. This is used by the bindings internally.
func UnsafeNetAddressMetaFromGlibNone(p unsafe.Pointer) *NetAddressMeta {
	wrapped := UnsafeNetAddressMetaFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}

	log.Println("WARNING: not attaching a finalizer to NetAddressMeta because no cgo ref function or copy method is available. This may leak memory. Please file an issue")
	return wrapped
}

// UnsafeNetAddressMetaFromGlibFull is used to convert raw C.GstNetAddressMeta pointers to go while taking ownership. This is used by the bindings internally.
func UnsafeNetAddressMetaFromGlibFull(p unsafe.Pointer) *NetAddressMeta {
	wrapped := UnsafeNetAddressMetaFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}
	runtime.SetFinalizer(
		wrapped.netAddressMeta,
		func (intern *netAddressMeta) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeNetAddressMetaFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NetAddressMeta] is expected to work anymore.
func UnsafeNetAddressMetaFree(n *NetAddressMeta) {
	C.free(unsafe.Pointer(n.native))
	runtime.SetFinalizer(n.netAddressMeta, nil)
}

// UnsafeNetAddressMetaToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNetAddressMetaToGlibNone(n *NetAddressMeta) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// UnsafeNetAddressMetaToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeNetAddressMetaToGlibFull(n *NetAddressMeta) unsafe.Pointer {
	if n == nil {
		return nil
	}
	runtime.SetFinalizer(n.netAddressMeta, nil)
	_p := unsafe.Pointer(n.native)
	n.native = nil // NetAddressMeta is invalid from here on
	return _p
}

// NetAddressMetaGetInfo wraps gst_net_address_meta_get_info
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetaddressmeta.html#gst_net_address_meta_get_info
func NetAddressMetaGetInfo() *gst.MetaInfo {
	var cret *C.GstMetaInfo // return, none, converted

	cret = C.gst_net_address_meta_get_info()

	var goret *gst.MetaInfo

	goret = gst.UnsafeMetaInfoFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// NetClientClockClass wraps GstNetClientClockClass
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#GstNetClientClockClass
// 
// NetClientClockClass is the type struct for [NetClientClock]
type NetClientClockClass struct {
	*netClientClockClass
}

// netClientClockClass is the struct that's finalized
type netClientClockClass struct {
	native *C.GstNetClientClockClass
}

// UnsafeNetClientClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NetClientClockClass) instance() *C.GstNetClientClockClass {
	if n == nil {
		return nil
	}
	return n.native
}

// UnsafeNetClientClockClassFromGlibBorrow is used to convert raw C.GstNetClientClockClass pointers to go. This is used by the bindings internally.
func UnsafeNetClientClockClassFromGlibBorrow(p unsafe.Pointer) *NetClientClockClass {
	if p == nil {
		return nil
	}
	return &NetClientClockClass{&netClientClockClass{(*C.GstNetClientClockClass)(p)}}
}

// UnsafeNetClientClockClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NetClientClockClass] is expected to work anymore.
func UnsafeNetClientClockClassFree(n *NetClientClockClass) {
	C.free(unsafe.Pointer(n.native))
	runtime.SetFinalizer(n.netClientClockClass, nil)
}

// UnsafeNetClientClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNetClientClockClassToGlibNone(n *NetClientClockClass) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (n *NetClientClockClass) ParentClass() *gst.SystemClockClass {
	parent := gst.UnsafeSystemClockClassFromGlibBorrow(UnsafeNetClientClockClassToGlibNone(n))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *NetClientClockClass) {}, n)
	return parent
}

// NetControlMessageMeta wraps GstNetControlMessageMeta
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetcontrolmessagemeta.html#GstNetControlMessageMeta
type NetControlMessageMeta struct {
	*netControlMessageMeta
}

// netControlMessageMeta is the struct that's finalized
type netControlMessageMeta struct {
	native *C.GstNetControlMessageMeta
}

// UnsafeNetControlMessageMetaToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NetControlMessageMeta) instance() *C.GstNetControlMessageMeta {
	if n == nil {
		return nil
	}
	return n.native
}

// UnsafeNetControlMessageMetaFromGlibBorrow is used to convert raw C.GstNetControlMessageMeta pointers to go. This is used by the bindings internally.
func UnsafeNetControlMessageMetaFromGlibBorrow(p unsafe.Pointer) *NetControlMessageMeta {
	if p == nil {
		return nil
	}
	return &NetControlMessageMeta{&netControlMessageMeta{(*C.GstNetControlMessageMeta)(p)}}
}

// UnsafeNetControlMessageMetaFromGlibNone is used to convert raw C.GstNetControlMessageMeta pointers to go without transferring ownership. This is used by the bindings internally.
func UnsafeNetControlMessageMetaFromGlibNone(p unsafe.Pointer) *NetControlMessageMeta {
	wrapped := UnsafeNetControlMessageMetaFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}

	log.Println("WARNING: not attaching a finalizer to NetControlMessageMeta because no cgo ref function or copy method is available. This may leak memory. Please file an issue")
	return wrapped
}

// UnsafeNetControlMessageMetaFromGlibFull is used to convert raw C.GstNetControlMessageMeta pointers to go while taking ownership. This is used by the bindings internally.
func UnsafeNetControlMessageMetaFromGlibFull(p unsafe.Pointer) *NetControlMessageMeta {
	wrapped := UnsafeNetControlMessageMetaFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}
	runtime.SetFinalizer(
		wrapped.netControlMessageMeta,
		func (intern *netControlMessageMeta) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeNetControlMessageMetaFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NetControlMessageMeta] is expected to work anymore.
func UnsafeNetControlMessageMetaFree(n *NetControlMessageMeta) {
	C.free(unsafe.Pointer(n.native))
	runtime.SetFinalizer(n.netControlMessageMeta, nil)
}

// UnsafeNetControlMessageMetaToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNetControlMessageMetaToGlibNone(n *NetControlMessageMeta) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// UnsafeNetControlMessageMetaToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeNetControlMessageMetaToGlibFull(n *NetControlMessageMeta) unsafe.Pointer {
	if n == nil {
		return nil
	}
	runtime.SetFinalizer(n.netControlMessageMeta, nil)
	_p := unsafe.Pointer(n.native)
	n.native = nil // NetControlMessageMeta is invalid from here on
	return _p
}

// NetControlMessageMetaGetInfo wraps gst_net_control_message_meta_get_info
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetcontrolmessagemeta.html#gst_net_control_message_meta_get_info
func NetControlMessageMetaGetInfo() *gst.MetaInfo {
	var cret *C.GstMetaInfo // return, none, converted

	cret = C.gst_net_control_message_meta_get_info()

	var goret *gst.MetaInfo

	goret = gst.UnsafeMetaInfoFromGlibNone(unsafe.Pointer(cret))

	return goret
}

// NetTimePacket wraps GstNetTimePacket
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#GstNetTimePacket
type NetTimePacket struct {
	*netTimePacket
}

// netTimePacket is the struct that's finalized
type netTimePacket struct {
	native *C.GstNetTimePacket
}

// UnsafeNetTimePacketToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NetTimePacket) instance() *C.GstNetTimePacket {
	if n == nil {
		return nil
	}
	return n.native
}

var _ gobject.GoValueInitializer = (*NetTimePacket)(nil)

func marshalNetTimePacket(p unsafe.Pointer) (interface{}, error) {
	b := gobject.ValueFromNative(p).Boxed()
	return UnsafeNetTimePacketFromGlibNone(b), nil
}

func (r *NetTimePacket) GoValueType() gobject.Type {
	return TypeNetTimePacket
}

func (r *NetTimePacket) SetGoValue(v *gobject.Value) {
	v.SetBoxed(unsafe.Pointer(r.instance()))
}

// UnsafeNetTimePacketFromGlibBorrow is used to convert raw C.GstNetTimePacket pointers to go. This is used by the bindings internally.
func UnsafeNetTimePacketFromGlibBorrow(p unsafe.Pointer) *NetTimePacket {
	if p == nil {
		return nil
	}
	return &NetTimePacket{&netTimePacket{(*C.GstNetTimePacket)(p)}}
}

// UnsafeNetTimePacketFromGlibNone is used to convert raw C.GstNetTimePacket pointers to go without transferring ownership. This is used by the bindings internally.
func UnsafeNetTimePacketFromGlibNone(p unsafe.Pointer) *NetTimePacket {
	wrapped := UnsafeNetTimePacketFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}

	return wrapped.Copy() // create an owned copy

}

// UnsafeNetTimePacketFromGlibFull is used to convert raw C.GstNetTimePacket pointers to go while taking ownership. This is used by the bindings internally.
func UnsafeNetTimePacketFromGlibFull(p unsafe.Pointer) *NetTimePacket {
	wrapped := UnsafeNetTimePacketFromGlibBorrow(p)
	if wrapped == nil {
		return nil
	}
	runtime.SetFinalizer(
		wrapped.netTimePacket,
		func (intern *netTimePacket) {
			C.gst_net_time_packet_free(intern.native)
		},
	)
	return wrapped
}

// UnsafeNetTimePacketFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NetTimePacket] is expected to work anymore.
func UnsafeNetTimePacketFree(n *NetTimePacket) {
	C.gst_net_time_packet_free(n.native)
	runtime.SetFinalizer(n.netTimePacket, nil)
}

// UnsafeNetTimePacketToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNetTimePacketToGlibNone(n *NetTimePacket) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// UnsafeNetTimePacketToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeNetTimePacketToGlibFull(n *NetTimePacket) unsafe.Pointer {
	if n == nil {
		return nil
	}
	runtime.SetFinalizer(n.netTimePacket, nil)
	_p := unsafe.Pointer(n.native)
	n.native = nil // NetTimePacket is invalid from here on
	return _p
}

// NewNetTimePacket wraps gst_net_time_packet_new
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#gst_net_time_packet_new
func NewNetTimePacket(buffer [16]uint8) *NetTimePacket {
	var carg1 *C.guint8           // in, none, array fixed size (inner: guint8, size: 16)
	var cret  *C.GstNetTimePacket // return, full, converted

	{
		var carr [16]C.guint8
		for i := range 16 {
			carr[i] = C.guint8(buffer[i])
			carg1 = unsafe.SliceData(carr[:])
		}
	}

	cret = C.gst_net_time_packet_new(carg1)
	runtime.KeepAlive(buffer)

	var goret *NetTimePacket

	goret = UnsafeNetTimePacketFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// NetTimePacketReceive wraps gst_net_time_packet_receive
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#gst_net_time_packet_receive
func NetTimePacketReceive(socket gio.Socket) (gio.SocketAddress, *NetTimePacket, error) {
	var carg1 *C.GSocket          // in, none, converted
	var carg2 *C.GSocketAddress   // out, full, converted
	var cret  *C.GstNetTimePacket // return, full, converted
	var _cerr *C.GError           // out, full, converted, nullable

	carg1 = (*C.GSocket)(gio.UnsafeSocketToGlibNone(socket))

	cret = C.gst_net_time_packet_receive(carg1, &carg2, &_cerr)
	runtime.KeepAlive(socket)

	var srcAddress gio.SocketAddress
	var goret      *NetTimePacket
	var _goerr     error

	srcAddress = gio.UnsafeSocketAddressFromGlibFull(unsafe.Pointer(carg2))
	goret = UnsafeNetTimePacketFromGlibFull(unsafe.Pointer(cret))
	if _cerr != nil {
		_goerr = glib.UnsafeErrorFromGlibFull(unsafe.Pointer(_cerr))
	}

	return srcAddress, goret, _goerr
}

// Copy wraps gst_net_time_packet_copy
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#gst_net_time_packet_copy
func (packet *NetTimePacket) Copy() *NetTimePacket {
	var carg0 *C.GstNetTimePacket // in, none, converted
	var cret  *C.GstNetTimePacket // return, full, converted

	carg0 = (*C.GstNetTimePacket)(UnsafeNetTimePacketToGlibNone(packet))

	cret = C.gst_net_time_packet_copy(carg0)
	runtime.KeepAlive(packet)

	var goret *NetTimePacket

	goret = UnsafeNetTimePacketFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// Send wraps gst_net_time_packet_send
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#gst_net_time_packet_send
func (packet *NetTimePacket) Send(socket gio.Socket, destAddress gio.SocketAddress) (bool, error) {
	var carg0 *C.GstNetTimePacket // in, none, converted
	var carg1 *C.GSocket          // in, none, converted
	var carg2 *C.GSocketAddress   // in, none, converted
	var cret  C.gboolean          // return
	var _cerr *C.GError           // out, full, converted, nullable

	carg0 = (*C.GstNetTimePacket)(UnsafeNetTimePacketToGlibNone(packet))
	carg1 = (*C.GSocket)(gio.UnsafeSocketToGlibNone(socket))
	carg2 = (*C.GSocketAddress)(gio.UnsafeSocketAddressToGlibNone(destAddress))

	cret = C.gst_net_time_packet_send(carg0, carg1, carg2, &_cerr)
	runtime.KeepAlive(packet)
	runtime.KeepAlive(socket)
	runtime.KeepAlive(destAddress)

	var goret  bool
	var _goerr error

	if cret != 0 {
		goret = true
	}
	if _cerr != nil {
		_goerr = glib.UnsafeErrorFromGlibFull(unsafe.Pointer(_cerr))
	}

	return goret, _goerr
}

// Serialize wraps gst_net_time_packet_serialize
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimepacket.html#gst_net_time_packet_serialize
func (packet *NetTimePacket) Serialize() [16]uint8 {
	var carg0 *C.GstNetTimePacket // in, none, converted
	var cret  *C.guint8           // return, transfer: full, C Pointers: 1, Name: array[guint8], scope: , array (inner guint8 (*typesystem.CastablePrimitive), fixed-size: 16)

	carg0 = (*C.GstNetTimePacket)(UnsafeNetTimePacketToGlibNone(packet))

	cret = C.gst_net_time_packet_serialize(carg0)
	runtime.KeepAlive(packet)

	var goret [16]uint8

	_ = goret
	_ = cret
	panic("unimplemented conversion of [16]uint8 (guint8*) because of unknown reason")

	return goret
}

// NetTimeProviderClass wraps GstNetTimeProviderClass
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnettimeprovider.html#GstNetTimeProviderClass
// 
// NetTimeProviderClass is the type struct for [NetTimeProvider]
type NetTimeProviderClass struct {
	*netTimeProviderClass
}

// netTimeProviderClass is the struct that's finalized
type netTimeProviderClass struct {
	native *C.GstNetTimeProviderClass
}

// UnsafeNetTimeProviderClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NetTimeProviderClass) instance() *C.GstNetTimeProviderClass {
	if n == nil {
		return nil
	}
	return n.native
}

// UnsafeNetTimeProviderClassFromGlibBorrow is used to convert raw C.GstNetTimeProviderClass pointers to go. This is used by the bindings internally.
func UnsafeNetTimeProviderClassFromGlibBorrow(p unsafe.Pointer) *NetTimeProviderClass {
	if p == nil {
		return nil
	}
	return &NetTimeProviderClass{&netTimeProviderClass{(*C.GstNetTimeProviderClass)(p)}}
}

// UnsafeNetTimeProviderClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NetTimeProviderClass] is expected to work anymore.
func UnsafeNetTimeProviderClassFree(n *NetTimeProviderClass) {
	C.free(unsafe.Pointer(n.native))
	runtime.SetFinalizer(n.netTimeProviderClass, nil)
}

// UnsafeNetTimeProviderClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNetTimeProviderClassToGlibNone(n *NetTimeProviderClass) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (n *NetTimeProviderClass) ParentClass() *gst.ObjectClass {
	parent := gst.UnsafeObjectClassFromGlibBorrow(UnsafeNetTimeProviderClassToGlibNone(n))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *NetTimeProviderClass) {}, n)
	return parent
}

// NtpClockClass wraps GstNtpClockClass
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstnetclientclock.html#GstNtpClockClass
// 
// NtpClockClass is the type struct for [NtpClock]
type NtpClockClass struct {
	*ntpClockClass
}

// ntpClockClass is the struct that's finalized
type ntpClockClass struct {
	native *C.GstNtpClockClass
}

// UnsafeNtpClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (n *NtpClockClass) instance() *C.GstNtpClockClass {
	if n == nil {
		return nil
	}
	return n.native
}

// UnsafeNtpClockClassFromGlibBorrow is used to convert raw C.GstNtpClockClass pointers to go. This is used by the bindings internally.
func UnsafeNtpClockClassFromGlibBorrow(p unsafe.Pointer) *NtpClockClass {
	if p == nil {
		return nil
	}
	return &NtpClockClass{&ntpClockClass{(*C.GstNtpClockClass)(p)}}
}

// UnsafeNtpClockClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [NtpClockClass] is expected to work anymore.
func UnsafeNtpClockClassFree(n *NtpClockClass) {
	C.free(unsafe.Pointer(n.native))
	runtime.SetFinalizer(n.ntpClockClass, nil)
}

// UnsafeNtpClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeNtpClockClassToGlibNone(n *NtpClockClass) unsafe.Pointer {
	if n == nil {
		return nil
	}
	return unsafe.Pointer(n.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (n *NtpClockClass) ParentClass() *NetClientClockClass {
	parent := UnsafeNetClientClockClassFromGlibBorrow(UnsafeNtpClockClassToGlibNone(n))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *NtpClockClass) {}, n)
	return parent
}

// PtpClockClass wraps GstPtpClockClass
// 
// see also https://gstreamer.freedesktop.org/documentation/net/gstptpclock.html#GstPtpClockClass
// 
// PtpClockClass is the type struct for [PtpClock]
type PtpClockClass struct {
	*ptpClockClass
}

// ptpClockClass is the struct that's finalized
type ptpClockClass struct {
	native *C.GstPtpClockClass
}

// UnsafePtpClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func (p *PtpClockClass) instance() *C.GstPtpClockClass {
	if p == nil {
		return nil
	}
	return p.native
}

// UnsafePtpClockClassFromGlibBorrow is used to convert raw C.GstPtpClockClass pointers to go. This is used by the bindings internally.
func UnsafePtpClockClassFromGlibBorrow(p unsafe.Pointer) *PtpClockClass {
	if p == nil {
		return nil
	}
	return &PtpClockClass{&ptpClockClass{(*C.GstPtpClockClass)(p)}}
}

// UnsafePtpClockClassFree unrefs/frees the underlying resource. This can be used to remove the instance before the GC decides to do so.
// 
// After this is called, no other method on [PtpClockClass] is expected to work anymore.
func UnsafePtpClockClassFree(p *PtpClockClass) {
	C.free(unsafe.Pointer(p.native))
	runtime.SetFinalizer(p.ptpClockClass, nil)
}

// UnsafePtpClockClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafePtpClockClassToGlibNone(p *PtpClockClass) unsafe.Pointer {
	if p == nil {
		return nil
	}
	return unsafe.Pointer(p.native)
}

// ParentClass returns the type struct of the parent class of this type struct.
// This essentially casts the underlying c pointer.
func (p *PtpClockClass) ParentClass() *gst.SystemClockClass {
	parent := gst.UnsafeSystemClockClassFromGlibBorrow(UnsafePtpClockClassToGlibNone(p))
	// attach a cleanup to keep the instance alive as long as the parent is referenced
	runtime.AddCleanup(parent, func(_ *PtpClockClass) {}, p)
	return parent
}

