// Code generated by girgen. DO NOT EDIT.

package gstapp

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/gobject/v2"
	"github.com/go-gst/go-gst/pkg/gst"
	"github.com/go-gst/go-gst/pkg/gstbase"
)

// #cgo pkg-config: gstreamer-app-1.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gst/app/app.h>
import "C"

// GType values.
var (
	TypeAppLeakyType  = gobject.Type(C.gst_app_leaky_type_get_type())
	TypeAppStreamType = gobject.Type(C.gst_app_stream_type_get_type())
	TypeAppSink       = gobject.Type(C.gst_app_sink_get_type())
	TypeAppSrc        = gobject.Type(C.gst_app_src_get_type())
)

func init() {
	gobject.RegisterGValueMarshalers([]gobject.TypeMarshaler{
		gobject.TypeMarshaler{T: TypeAppLeakyType, F: marshalAppLeakyType},
		gobject.TypeMarshaler{T: TypeAppStreamType, F: marshalAppStreamType},
		gobject.TypeMarshaler{T: TypeAppSink, F: marshalAppSinkInstance},
		gobject.TypeMarshaler{T: TypeAppSrc, F: marshalAppSrcInstance},
	})
}

// AppLeakyType wraps GstAppLeakyType
//
// Buffer dropping scheme to avoid the element's internal queue to block when
// full.
type AppLeakyType C.int

const (
	// AppLeakyTypeNone wraps GST_APP_LEAKY_TYPE_NONE
	//
	// Not Leaky
	AppLeakyTypeNone AppLeakyType = 0
	// AppLeakyTypeUpstream wraps GST_APP_LEAKY_TYPE_UPSTREAM
	//
	// Leaky on upstream (new buffers)
	AppLeakyTypeUpstream AppLeakyType = 1
	// AppLeakyTypeDownstream wraps GST_APP_LEAKY_TYPE_DOWNSTREAM
	//
	// Leaky on downstream (old buffers)
	AppLeakyTypeDownstream AppLeakyType = 2
)

func marshalAppLeakyType(p unsafe.Pointer) (any, error) {
	return AppLeakyType(gobject.ValueFromNative(p).Enum()), nil
}

var _ gobject.GoValueInitializer = AppLeakyType(0)

func (e AppLeakyType) InitGoValue(v *gobject.Value) {
	v.Init(TypeAppLeakyType)
	v.SetEnum(int(e))
}

// AppStreamType wraps GstAppStreamType
//
// The stream type.
type AppStreamType C.int

const (
	// AppStreamTypeStream wraps GST_APP_STREAM_TYPE_STREAM
	//
	// No seeking is supported in the stream, such as a
	// live stream.
	AppStreamTypeStream AppStreamType = 0
	// AppStreamTypeSeekable wraps GST_APP_STREAM_TYPE_SEEKABLE
	//
	// The stream is seekable but seeking might not
	// be very fast, such as data from a webserver.
	AppStreamTypeSeekable AppStreamType = 1
	// AppStreamTypeRandomAccess wraps GST_APP_STREAM_TYPE_RANDOM_ACCESS
	//
	// The stream is seekable and seeking is fast,
	// such as in a local file.
	AppStreamTypeRandomAccess AppStreamType = 2
)

func marshalAppStreamType(p unsafe.Pointer) (any, error) {
	return AppStreamType(gobject.ValueFromNative(p).Enum()), nil
}

var _ gobject.GoValueInitializer = AppStreamType(0)

func (e AppStreamType) InitGoValue(v *gobject.Value) {
	v.Init(TypeAppStreamType)
	v.SetEnum(int(e))
}

// AppSinkInstance is the instance type used by all types extending GstAppSink. It is used internally by the bindings. Users should use the interface [AppSink] instead.
type AppSinkInstance struct {
	_ [0]func() // equal guard
	gstbase.BaseSinkInstance
	// implemented interfaces:
	gst.URIHandlerInstance
}

var _ AppSink = (*AppSinkInstance)(nil)

// AppSink wraps GstAppSink
//
// Appsink is a sink plugin that supports many different methods for making
// the application get a handle on the GStreamer data in a pipeline. Unlike
// most GStreamer elements, Appsink provides external API functions.
// 
// appsink can be used by linking to the gstappsink.h header file to access the
// methods or by using the appsink action signals and properties.
// 
// The normal way of retrieving samples from appsink is by using the
// gst_app_sink_pull_sample() and gst_app_sink_pull_preroll() methods.
// These methods block until a sample becomes available in the sink or when the
// sink is shut down or reaches EOS. There are also timed variants of these
// methods, gst_app_sink_try_pull_sample() and gst_app_sink_try_pull_preroll(),
// which accept a timeout parameter to limit the amount of time to wait.
// 
// Appsink will internally use a queue to collect buffers from the streaming
// thread. If the application is not pulling samples fast enough, this queue
// will consume a lot of memory over time. The "max-buffers", "max-time" and "max-bytes"
// properties can be used to limit the queue size. The "drop" property controls whether the
// streaming thread blocks or if older buffers are dropped when the maximum
// queue size is reached. Note that blocking the streaming thread can negatively
// affect real-time performance and should be avoided.
// 
// If a blocking behaviour is not desirable, setting the "emit-signals" property
// to %TRUE will make appsink emit the "new-sample" and "new-preroll" signals
// when a sample can be pulled without blocking.
// 
// The "caps" property on appsink can be used to control the formats that
// appsink can receive. This property can contain non-fixed caps, the format of
// the pulled samples can be obtained by getting the sample caps.
// 
// If one of the pull-preroll or pull-sample methods return %NULL, the appsink
// is stopped or in the EOS state. You can check for the EOS state with the
// "eos" property or with the gst_app_sink_is_eos() method.
// 
// The eos signal can also be used to be informed when the EOS state is reached
// to avoid polling.
type AppSink interface {
	gstbase.BaseSink
	gst.URIHandler
	upcastToGstAppSink() *AppSinkInstance

	// GetBufferListSupport wraps gst_app_sink_get_buffer_list_support
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if @appsink supports buffer lists.
	GetBufferListSupport() bool
	// GetCaps wraps gst_app_sink_get_caps
	// The function returns the following values:
	// 
	// 	- goret *gst.Caps 
	//
	// Get the configured caps on @appsink.
	GetCaps() *gst.Caps
	// GetDrop wraps gst_app_sink_get_drop
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if @appsink will drop old buffers when the maximum amount of queued
	// data is reached (meaning max buffers, time or bytes limit, whichever is hit first).
	GetDrop() bool
	// GetEmitSignals wraps gst_app_sink_get_emit_signals
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if appsink will emit the "new-preroll" and "new-sample" signals.
	GetEmitSignals() bool
	// GetMaxBuffers wraps gst_app_sink_get_max_buffers
	// The function returns the following values:
	// 
	// 	- goret uint 
	//
	// Get the maximum amount of buffers that can be queued in @appsink.
	GetMaxBuffers() uint
	// GetMaxBytes wraps gst_app_sink_get_max_bytes
	// The function returns the following values:
	// 
	// 	- goret uint64 
	//
	// Get the maximum total size, in bytes, that can be queued in @appsink.
	GetMaxBytes() uint64
	// GetMaxTime wraps gst_app_sink_get_max_time
	// The function returns the following values:
	// 
	// 	- goret gst.ClockTime 
	//
	// Get the maximum total duration that can be queued in @appsink.
	GetMaxTime() gst.ClockTime
	// GetWaitOnEos wraps gst_app_sink_get_wait_on_eos
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if @appsink will wait for all buffers to be consumed when an EOS is
	// received.
	GetWaitOnEos() bool
	// IsEos wraps gst_app_sink_is_eos
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if @appsink is EOS, which is when no more samples can be pulled because
	// an EOS event was received.
	// 
	// This function also returns %TRUE when the appsink is not in the PAUSED or
	// PLAYING state.
	IsEos() bool
	// PullPreroll wraps gst_app_sink_pull_preroll
	// The function returns the following values:
	// 
	// 	- goret *gst.Sample 
	//
	// Get the last preroll sample in @appsink. This was the sample that caused the
	// appsink to preroll in the PAUSED state.
	// 
	// This function is typically used when dealing with a pipeline in the PAUSED
	// state. Calling this function after doing a seek will give the sample right
	// after the seek position.
	// 
	// Calling this function will clear the internal reference to the preroll
	// buffer.
	// 
	// Note that the preroll sample will also be returned as the first sample
	// when calling gst_app_sink_pull_sample().
	// 
	// If an EOS event was received before any buffers, this function returns
	// %NULL. Use gst_app_sink_is_eos () to check for the EOS condition.
	// 
	// This function blocks until a preroll sample or EOS is received or the appsink
	// element is set to the READY/NULL state.
	PullPreroll() *gst.Sample
	// PullSample wraps gst_app_sink_pull_sample
	// The function returns the following values:
	// 
	// 	- goret *gst.Sample 
	//
	// This function blocks until a sample or EOS becomes available or the appsink
	// element is set to the READY/NULL state.
	// 
	// This function will only return samples when the appsink is in the PLAYING
	// state. All rendered buffers will be put in a queue so that the application
	// can pull samples at its own rate. Note that when the application does not
	// pull samples fast enough, the queued buffers could consume a lot of memory,
	// especially when dealing with raw video frames.
	// 
	// If an EOS event was received before any buffers, this function returns
	// %NULL. Use gst_app_sink_is_eos () to check for the EOS condition.
	PullSample() *gst.Sample
	// SetBufferListSupport wraps gst_app_sink_set_buffer_list_support
	// 
	// The function takes the following parameters:
	// 
	// 	- enableLists bool: enable or disable buffer list support 
	//
	// Instruct @appsink to enable or disable buffer list support.
	// 
	// For backwards-compatibility reasons applications need to opt in
	// to indicate that they will be able to handle buffer lists.
	SetBufferListSupport(bool)
	// SetCaps wraps gst_app_sink_set_caps
	// 
	// The function takes the following parameters:
	// 
	// 	- caps *gst.Caps (nullable): caps to set 
	//
	// Set the capabilities on the appsink element.  This function takes
	// a copy of the caps structure. After calling this method, the sink will only
	// accept caps that match @caps. If @caps is non-fixed, or incomplete,
	// you must check the caps on the samples to get the actual used caps.
	SetCaps(*gst.Caps)
	// SetDrop wraps gst_app_sink_set_drop
	// 
	// The function takes the following parameters:
	// 
	// 	- drop bool: the new state 
	//
	// Instruct @appsink to drop old buffers when the maximum amount of queued
	// data is reached, that is, when any configured limit is hit (max-buffers, max-time or max-bytes).
	SetDrop(bool)
	// SetEmitSignals wraps gst_app_sink_set_emit_signals
	// 
	// The function takes the following parameters:
	// 
	// 	- emit bool: the new state 
	//
	// Make appsink emit the "new-preroll" and "new-sample" signals. This option is
	// by default disabled because signal emission is expensive and unneeded when
	// the application prefers to operate in pull mode.
	SetEmitSignals(bool)
	// SetMaxBuffers wraps gst_app_sink_set_max_buffers
	// 
	// The function takes the following parameters:
	// 
	// 	- max uint: the maximum number of buffers to queue 
	//
	// Set the maximum amount of buffers that can be queued in @appsink. After this
	// amount of buffers are queued in appsink, any more buffers will block upstream
	// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
	// case new buffers will be discarded.
	SetMaxBuffers(uint)
	// SetMaxBytes wraps gst_app_sink_set_max_bytes
	// 
	// The function takes the following parameters:
	// 
	// 	- max uint64: the maximum total size of buffers to queue, in bytes 
	//
	// Set the maximum total size that can be queued in @appsink. After this
	// amount of buffers are queued in appsink, any more buffers will block upstream
	// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
	// case new buffers will be discarded.
	SetMaxBytes(uint64)
	// SetMaxTime wraps gst_app_sink_set_max_time
	// 
	// The function takes the following parameters:
	// 
	// 	- max gst.ClockTime: the maximum total duration to queue 
	//
	// Set the maximum total duration that can be queued in @appsink. After this
	// amount of buffers are queued in appsink, any more buffers will block upstream
	// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
	// case new buffers will be discarded.
	SetMaxTime(gst.ClockTime)
	// SetWaitOnEos wraps gst_app_sink_set_wait_on_eos
	// 
	// The function takes the following parameters:
	// 
	// 	- wait bool: the new state 
	//
	// Instruct @appsink to wait for all buffers to be consumed when an EOS is received.
	SetWaitOnEos(bool)
	// TryPullPreroll wraps gst_app_sink_try_pull_preroll
	// 
	// The function takes the following parameters:
	// 
	// 	- timeout gst.ClockTime: the maximum amount of time to wait for the preroll sample 
	// 
	// The function returns the following values:
	// 
	// 	- goret *gst.Sample 
	//
	// Get the last preroll sample in @appsink. This was the sample that caused the
	// appsink to preroll in the PAUSED state.
	// 
	// This function is typically used when dealing with a pipeline in the PAUSED
	// state. Calling this function after doing a seek will give the sample right
	// after the seek position.
	// 
	// Calling this function will clear the internal reference to the preroll
	// buffer.
	// 
	// Note that the preroll sample will also be returned as the first sample
	// when calling gst_app_sink_pull_sample().
	// 
	// If an EOS event was received before any buffers or the timeout expires,
	// this function returns %NULL. Use gst_app_sink_is_eos () to check for the EOS
	// condition.
	// 
	// This function blocks until a preroll sample or EOS is received, the appsink
	// element is set to the READY/NULL state, or the timeout expires.
	TryPullPreroll(gst.ClockTime) *gst.Sample
	// TryPullSample wraps gst_app_sink_try_pull_sample
	// 
	// The function takes the following parameters:
	// 
	// 	- timeout gst.ClockTime: the maximum amount of time to wait for a sample 
	// 
	// The function returns the following values:
	// 
	// 	- goret *gst.Sample 
	//
	// This function blocks until a sample or EOS becomes available or the appsink
	// element is set to the READY/NULL state or the timeout expires.
	// 
	// This function will only return samples when the appsink is in the PLAYING
	// state. All rendered buffers will be put in a queue so that the application
	// can pull samples at its own rate. Note that when the application does not
	// pull samples fast enough, the queued buffers could consume a lot of memory,
	// especially when dealing with raw video frames.
	// 
	// If an EOS event was received before any buffers or the timeout expires,
	// this function returns %NULL. Use gst_app_sink_is_eos () to check for the EOS
	// condition.
	TryPullSample(gst.ClockTime) *gst.Sample
}

func unsafeWrapAppSink(base *gobject.ObjectInstance) *AppSinkInstance {
	return &AppSinkInstance{
		BaseSinkInstance: gstbase.BaseSinkInstance{
			ElementInstance: gst.ElementInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
		URIHandlerInstance: gst.URIHandlerInstance{
			Instance: *base,
		},
	}
}

func marshalAppSinkInstance(p unsafe.Pointer) (any, error) {
	return unsafeWrapAppSink(gobject.ValueFromNative(p).Object()), nil
}

// UnsafeAppSinkFromGlibNone is used to convert raw GstAppSink pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeAppSinkFromGlibNone(c unsafe.Pointer) AppSink {
	return gobject.UnsafeObjectFromGlibNone(c).(AppSink)
}

// UnsafeAppSinkFromGlibFull is used to convert raw GstAppSink pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeAppSinkFromGlibFull(c unsafe.Pointer) AppSink {
	return gobject.UnsafeObjectFromGlibFull(c).(AppSink)
}

func (a *AppSinkInstance) upcastToGstAppSink() *AppSinkInstance {
	return a
}

// UnsafeAppSinkToGlibNone is used to convert the instance to it's C value GstAppSink. This is used by the bindings internally.
func UnsafeAppSinkToGlibNone(c AppSink) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeAppSinkToGlibFull is used to convert the instance to it's C value GstAppSink, while removeing the finalizer. This is used by the bindings internally.
func UnsafeAppSinkToGlibFull(c AppSink) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// GetBufferListSupport wraps gst_app_sink_get_buffer_list_support
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if @appsink supports buffer lists.
func (appsink *AppSinkInstance) GetBufferListSupport() bool {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.gboolean    // return

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_buffer_list_support(carg0)
	runtime.KeepAlive(appsink)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// GetCaps wraps gst_app_sink_get_caps
// The function returns the following values:
// 
// 	- goret *gst.Caps 
//
// Get the configured caps on @appsink.
func (appsink *AppSinkInstance) GetCaps() *gst.Caps {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  *C.GstCaps    // return, full, converted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_caps(carg0)
	runtime.KeepAlive(appsink)

	var goret *gst.Caps

	goret = gst.UnsafeCapsFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// GetDrop wraps gst_app_sink_get_drop
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if @appsink will drop old buffers when the maximum amount of queued
// data is reached (meaning max buffers, time or bytes limit, whichever is hit first).
func (appsink *AppSinkInstance) GetDrop() bool {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.gboolean    // return

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_drop(carg0)
	runtime.KeepAlive(appsink)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// GetEmitSignals wraps gst_app_sink_get_emit_signals
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if appsink will emit the "new-preroll" and "new-sample" signals.
func (appsink *AppSinkInstance) GetEmitSignals() bool {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.gboolean    // return

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_emit_signals(carg0)
	runtime.KeepAlive(appsink)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// GetMaxBuffers wraps gst_app_sink_get_max_buffers
// The function returns the following values:
// 
// 	- goret uint 
//
// Get the maximum amount of buffers that can be queued in @appsink.
func (appsink *AppSinkInstance) GetMaxBuffers() uint {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.guint       // return, none, casted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_max_buffers(carg0)
	runtime.KeepAlive(appsink)

	var goret uint

	goret = uint(cret)

	return goret
}

// GetMaxBytes wraps gst_app_sink_get_max_bytes
// The function returns the following values:
// 
// 	- goret uint64 
//
// Get the maximum total size, in bytes, that can be queued in @appsink.
func (appsink *AppSinkInstance) GetMaxBytes() uint64 {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.guint64     // return, none, casted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_max_bytes(carg0)
	runtime.KeepAlive(appsink)

	var goret uint64

	goret = uint64(cret)

	return goret
}

// GetMaxTime wraps gst_app_sink_get_max_time
// The function returns the following values:
// 
// 	- goret gst.ClockTime 
//
// Get the maximum total duration that can be queued in @appsink.
func (appsink *AppSinkInstance) GetMaxTime() gst.ClockTime {
	var carg0 *C.GstAppSink  // in, none, converted
	var cret  C.GstClockTime // return, none, casted, alias

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_max_time(carg0)
	runtime.KeepAlive(appsink)

	var goret gst.ClockTime

	goret = gst.ClockTime(cret)

	return goret
}

// GetWaitOnEos wraps gst_app_sink_get_wait_on_eos
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if @appsink will wait for all buffers to be consumed when an EOS is
// received.
func (appsink *AppSinkInstance) GetWaitOnEos() bool {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.gboolean    // return

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_get_wait_on_eos(carg0)
	runtime.KeepAlive(appsink)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// IsEos wraps gst_app_sink_is_eos
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if @appsink is EOS, which is when no more samples can be pulled because
// an EOS event was received.
// 
// This function also returns %TRUE when the appsink is not in the PAUSED or
// PLAYING state.
func (appsink *AppSinkInstance) IsEos() bool {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  C.gboolean    // return

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_is_eos(carg0)
	runtime.KeepAlive(appsink)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// PullPreroll wraps gst_app_sink_pull_preroll
// The function returns the following values:
// 
// 	- goret *gst.Sample 
//
// Get the last preroll sample in @appsink. This was the sample that caused the
// appsink to preroll in the PAUSED state.
// 
// This function is typically used when dealing with a pipeline in the PAUSED
// state. Calling this function after doing a seek will give the sample right
// after the seek position.
// 
// Calling this function will clear the internal reference to the preroll
// buffer.
// 
// Note that the preroll sample will also be returned as the first sample
// when calling gst_app_sink_pull_sample().
// 
// If an EOS event was received before any buffers, this function returns
// %NULL. Use gst_app_sink_is_eos () to check for the EOS condition.
// 
// This function blocks until a preroll sample or EOS is received or the appsink
// element is set to the READY/NULL state.
func (appsink *AppSinkInstance) PullPreroll() *gst.Sample {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  *C.GstSample  // return, full, converted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_pull_preroll(carg0)
	runtime.KeepAlive(appsink)

	var goret *gst.Sample

	goret = gst.UnsafeSampleFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// PullSample wraps gst_app_sink_pull_sample
// The function returns the following values:
// 
// 	- goret *gst.Sample 
//
// This function blocks until a sample or EOS becomes available or the appsink
// element is set to the READY/NULL state.
// 
// This function will only return samples when the appsink is in the PLAYING
// state. All rendered buffers will be put in a queue so that the application
// can pull samples at its own rate. Note that when the application does not
// pull samples fast enough, the queued buffers could consume a lot of memory,
// especially when dealing with raw video frames.
// 
// If an EOS event was received before any buffers, this function returns
// %NULL. Use gst_app_sink_is_eos () to check for the EOS condition.
func (appsink *AppSinkInstance) PullSample() *gst.Sample {
	var carg0 *C.GstAppSink // in, none, converted
	var cret  *C.GstSample  // return, full, converted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))

	cret = C.gst_app_sink_pull_sample(carg0)
	runtime.KeepAlive(appsink)

	var goret *gst.Sample

	goret = gst.UnsafeSampleFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// SetBufferListSupport wraps gst_app_sink_set_buffer_list_support
// 
// The function takes the following parameters:
// 
// 	- enableLists bool: enable or disable buffer list support 
//
// Instruct @appsink to enable or disable buffer list support.
// 
// For backwards-compatibility reasons applications need to opt in
// to indicate that they will be able to handle buffer lists.
func (appsink *AppSinkInstance) SetBufferListSupport(enableLists bool) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.gboolean    // in

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	if enableLists {
		carg1 = C.TRUE
	}

	C.gst_app_sink_set_buffer_list_support(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(enableLists)
}

// SetCaps wraps gst_app_sink_set_caps
// 
// The function takes the following parameters:
// 
// 	- caps *gst.Caps (nullable): caps to set 
//
// Set the capabilities on the appsink element.  This function takes
// a copy of the caps structure. After calling this method, the sink will only
// accept caps that match @caps. If @caps is non-fixed, or incomplete,
// you must check the caps on the samples to get the actual used caps.
func (appsink *AppSinkInstance) SetCaps(caps *gst.Caps) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 *C.GstCaps    // in, none, converted, nullable

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	if caps != nil {
		carg1 = (*C.GstCaps)(gst.UnsafeCapsToGlibNone(caps))
	}

	C.gst_app_sink_set_caps(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(caps)
}

// SetDrop wraps gst_app_sink_set_drop
// 
// The function takes the following parameters:
// 
// 	- drop bool: the new state 
//
// Instruct @appsink to drop old buffers when the maximum amount of queued
// data is reached, that is, when any configured limit is hit (max-buffers, max-time or max-bytes).
func (appsink *AppSinkInstance) SetDrop(drop bool) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.gboolean    // in

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	if drop {
		carg1 = C.TRUE
	}

	C.gst_app_sink_set_drop(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(drop)
}

// SetEmitSignals wraps gst_app_sink_set_emit_signals
// 
// The function takes the following parameters:
// 
// 	- emit bool: the new state 
//
// Make appsink emit the "new-preroll" and "new-sample" signals. This option is
// by default disabled because signal emission is expensive and unneeded when
// the application prefers to operate in pull mode.
func (appsink *AppSinkInstance) SetEmitSignals(emit bool) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.gboolean    // in

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	if emit {
		carg1 = C.TRUE
	}

	C.gst_app_sink_set_emit_signals(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(emit)
}

// SetMaxBuffers wraps gst_app_sink_set_max_buffers
// 
// The function takes the following parameters:
// 
// 	- max uint: the maximum number of buffers to queue 
//
// Set the maximum amount of buffers that can be queued in @appsink. After this
// amount of buffers are queued in appsink, any more buffers will block upstream
// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
// case new buffers will be discarded.
func (appsink *AppSinkInstance) SetMaxBuffers(max uint) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.guint       // in, none, casted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	carg1 = C.guint(max)

	C.gst_app_sink_set_max_buffers(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(max)
}

// SetMaxBytes wraps gst_app_sink_set_max_bytes
// 
// The function takes the following parameters:
// 
// 	- max uint64: the maximum total size of buffers to queue, in bytes 
//
// Set the maximum total size that can be queued in @appsink. After this
// amount of buffers are queued in appsink, any more buffers will block upstream
// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
// case new buffers will be discarded.
func (appsink *AppSinkInstance) SetMaxBytes(max uint64) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.guint64     // in, none, casted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	carg1 = C.guint64(max)

	C.gst_app_sink_set_max_bytes(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(max)
}

// SetMaxTime wraps gst_app_sink_set_max_time
// 
// The function takes the following parameters:
// 
// 	- max gst.ClockTime: the maximum total duration to queue 
//
// Set the maximum total duration that can be queued in @appsink. After this
// amount of buffers are queued in appsink, any more buffers will block upstream
// elements until a sample is pulled from @appsink, unless 'drop' is set, in which
// case new buffers will be discarded.
func (appsink *AppSinkInstance) SetMaxTime(max gst.ClockTime) {
	var carg0 *C.GstAppSink  // in, none, converted
	var carg1 C.GstClockTime // in, none, casted, alias

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	carg1 = C.GstClockTime(max)

	C.gst_app_sink_set_max_time(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(max)
}

// SetWaitOnEos wraps gst_app_sink_set_wait_on_eos
// 
// The function takes the following parameters:
// 
// 	- wait bool: the new state 
//
// Instruct @appsink to wait for all buffers to be consumed when an EOS is received.
func (appsink *AppSinkInstance) SetWaitOnEos(wait bool) {
	var carg0 *C.GstAppSink // in, none, converted
	var carg1 C.gboolean    // in

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	if wait {
		carg1 = C.TRUE
	}

	C.gst_app_sink_set_wait_on_eos(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(wait)
}

// TryPullPreroll wraps gst_app_sink_try_pull_preroll
// 
// The function takes the following parameters:
// 
// 	- timeout gst.ClockTime: the maximum amount of time to wait for the preroll sample 
// 
// The function returns the following values:
// 
// 	- goret *gst.Sample 
//
// Get the last preroll sample in @appsink. This was the sample that caused the
// appsink to preroll in the PAUSED state.
// 
// This function is typically used when dealing with a pipeline in the PAUSED
// state. Calling this function after doing a seek will give the sample right
// after the seek position.
// 
// Calling this function will clear the internal reference to the preroll
// buffer.
// 
// Note that the preroll sample will also be returned as the first sample
// when calling gst_app_sink_pull_sample().
// 
// If an EOS event was received before any buffers or the timeout expires,
// this function returns %NULL. Use gst_app_sink_is_eos () to check for the EOS
// condition.
// 
// This function blocks until a preroll sample or EOS is received, the appsink
// element is set to the READY/NULL state, or the timeout expires.
func (appsink *AppSinkInstance) TryPullPreroll(timeout gst.ClockTime) *gst.Sample {
	var carg0 *C.GstAppSink  // in, none, converted
	var carg1 C.GstClockTime // in, none, casted, alias
	var cret  *C.GstSample   // return, full, converted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	carg1 = C.GstClockTime(timeout)

	cret = C.gst_app_sink_try_pull_preroll(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(timeout)

	var goret *gst.Sample

	goret = gst.UnsafeSampleFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// TryPullSample wraps gst_app_sink_try_pull_sample
// 
// The function takes the following parameters:
// 
// 	- timeout gst.ClockTime: the maximum amount of time to wait for a sample 
// 
// The function returns the following values:
// 
// 	- goret *gst.Sample 
//
// This function blocks until a sample or EOS becomes available or the appsink
// element is set to the READY/NULL state or the timeout expires.
// 
// This function will only return samples when the appsink is in the PLAYING
// state. All rendered buffers will be put in a queue so that the application
// can pull samples at its own rate. Note that when the application does not
// pull samples fast enough, the queued buffers could consume a lot of memory,
// especially when dealing with raw video frames.
// 
// If an EOS event was received before any buffers or the timeout expires,
// this function returns %NULL. Use gst_app_sink_is_eos () to check for the EOS
// condition.
func (appsink *AppSinkInstance) TryPullSample(timeout gst.ClockTime) *gst.Sample {
	var carg0 *C.GstAppSink  // in, none, converted
	var carg1 C.GstClockTime // in, none, casted, alias
	var cret  *C.GstSample   // return, full, converted

	carg0 = (*C.GstAppSink)(UnsafeAppSinkToGlibNone(appsink))
	carg1 = C.GstClockTime(timeout)

	cret = C.gst_app_sink_try_pull_sample(carg0, carg1)
	runtime.KeepAlive(appsink)
	runtime.KeepAlive(timeout)

	var goret *gst.Sample

	goret = gst.UnsafeSampleFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// AppSrcInstance is the instance type used by all types extending GstAppSrc. It is used internally by the bindings. Users should use the interface [AppSrc] instead.
type AppSrcInstance struct {
	_ [0]func() // equal guard
	gstbase.BaseSrcInstance
	// implemented interfaces:
	gst.URIHandlerInstance
}

var _ AppSrc = (*AppSrcInstance)(nil)

// AppSrc wraps GstAppSrc
//
// The appsrc element can be used by applications to insert data into a
// GStreamer pipeline. Unlike most GStreamer elements, appsrc provides
// external API functions.
// 
// appsrc can be used by linking with the libgstapp library to access the
// methods directly or by using the appsrc action signals.
// 
// Before operating appsrc, the caps property must be set to fixed caps
// describing the format of the data that will be pushed with appsrc. An
// exception to this is when pushing buffers with unknown caps, in which case no
// caps should be set. This is typically true of file-like sources that push raw
// byte buffers. If you don't want to explicitly set the caps, you can use
// gst_app_src_push_sample. This method gets the caps associated with the
// sample and sets them on the appsrc replacing any previously set caps (if
// different from sample's caps).
// 
// The main way of handing data to the appsrc element is by calling the
// gst_app_src_push_buffer() method or by emitting the push-buffer action signal.
// This will put the buffer onto a queue from which appsrc will read from in its
// streaming thread. It is important to note that data transport will not happen
// from the thread that performed the push-buffer call.
// 
// The "max-bytes", "max-buffers" and "max-time" properties control how much
// data can be queued in appsrc before appsrc considers the queue full. A
// filled internal queue will always signal the "enough-data" signal, which
// signals the application that it should stop pushing data into appsrc. The
// "block" property will cause appsrc to block the push-buffer method until
// free data becomes available again.
// 
// When the internal queue is running out of data, the "need-data" signal is
// emitted, which signals the application that it should start pushing more data
// into appsrc.
// 
// In addition to the "need-data" and "enough-data" signals, appsrc can emit the
// "seek-data" signal when the "stream-mode" property is set to "seekable" or
// "random-access". The signal argument will contain the new desired position in
// the stream expressed in the unit set with the "format" property. After
// receiving the seek-data signal, the application should push-buffers from the
// new position.
// 
// These signals allow the application to operate the appsrc in two different
// ways:
// 
// The push mode, in which the application repeatedly calls the push-buffer/push-sample
// method with a new buffer/sample. Optionally, the queue size in the appsrc
// can be controlled with the enough-data and need-data signals by respectively
// stopping/starting the push-buffer/push-sample calls. This is a typical
// mode of operation for the stream-type "stream" and "seekable". Use this
// mode when implementing various network protocols or hardware devices.
// 
// The pull mode, in which the need-data signal triggers the next push-buffer call.
// This mode is typically used in the "random-access" stream-type. Use this
// mode for file access or other randomly accessible sources. In this mode, a
// buffer of exactly the amount of bytes given by the need-data signal should be
// pushed into appsrc.
// 
// In all modes, the size property on appsrc should contain the total stream
// size in bytes. Setting this property is mandatory in the random-access mode.
// For the stream and seekable modes, setting this property is optional but
// recommended.
// 
// When the application has finished pushing data into appsrc, it should call
// gst_app_src_end_of_stream() or emit the end-of-stream action signal. After
// this call, no more buffers can be pushed into appsrc until a flushing seek
// occurs or the state of the appsrc has gone through READY.
type AppSrc interface {
	gstbase.BaseSrc
	gst.URIHandler
	upcastToGstAppSrc() *AppSrcInstance

	// EndOfStream wraps gst_app_src_end_of_stream
	// The function returns the following values:
	// 
	// 	- goret gst.FlowReturn 
	//
	// Indicates to the appsrc element that the last buffer queued in the
	// element is the last buffer of the stream.
	EndOfStream() gst.FlowReturn
	// GetCaps wraps gst_app_src_get_caps
	// The function returns the following values:
	// 
	// 	- goret *gst.Caps 
	//
	// Get the configured caps on @appsrc.
	GetCaps() *gst.Caps
	// GetCurrentLevelBuffers wraps gst_app_src_get_current_level_buffers
	// The function returns the following values:
	// 
	// 	- goret uint64 
	//
	// Get the number of currently queued buffers inside @appsrc.
	GetCurrentLevelBuffers() uint64
	// GetCurrentLevelBytes wraps gst_app_src_get_current_level_bytes
	// The function returns the following values:
	// 
	// 	- goret uint64 
	//
	// Get the number of currently queued bytes inside @appsrc.
	GetCurrentLevelBytes() uint64
	// GetCurrentLevelTime wraps gst_app_src_get_current_level_time
	// The function returns the following values:
	// 
	// 	- goret gst.ClockTime 
	//
	// Get the amount of currently queued time inside @appsrc.
	GetCurrentLevelTime() gst.ClockTime
	// GetDuration wraps gst_app_src_get_duration
	// The function returns the following values:
	// 
	// 	- goret gst.ClockTime 
	//
	// Get the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
	// not known.
	GetDuration() gst.ClockTime
	// GetEmitSignals wraps gst_app_src_get_emit_signals
	// The function returns the following values:
	// 
	// 	- goret bool 
	//
	// Check if appsrc will emit the "new-preroll" and "new-buffer" signals.
	GetEmitSignals() bool
	// GetLatency wraps gst_app_src_get_latency
	// The function returns the following values:
	// 
	// 	- min uint64: the min latency 
	// 	- max uint64: the max latency 
	//
	// Retrieve the min and max latencies in @min and @max respectively.
	GetLatency() (uint64, uint64)
	// GetLeakyType wraps gst_app_src_get_leaky_type
	// The function returns the following values:
	// 
	// 	- goret AppLeakyType 
	//
	// Returns the currently set #GstAppLeakyType. See gst_app_src_set_leaky_type()
	// for more details.
	GetLeakyType() AppLeakyType
	// GetMaxBuffers wraps gst_app_src_get_max_buffers
	// The function returns the following values:
	// 
	// 	- goret uint64 
	//
	// Get the maximum amount of buffers that can be queued in @appsrc.
	GetMaxBuffers() uint64
	// GetMaxBytes wraps gst_app_src_get_max_bytes
	// The function returns the following values:
	// 
	// 	- goret uint64 
	//
	// Get the maximum amount of bytes that can be queued in @appsrc.
	GetMaxBytes() uint64
	// GetMaxTime wraps gst_app_src_get_max_time
	// The function returns the following values:
	// 
	// 	- goret gst.ClockTime 
	//
	// Get the maximum amount of time that can be queued in @appsrc.
	GetMaxTime() gst.ClockTime
	// GetSize wraps gst_app_src_get_size
	// The function returns the following values:
	// 
	// 	- goret int64 
	//
	// Get the size of the stream in bytes. A value of -1 means that the size is
	// not known.
	GetSize() int64
	// GetStreamType wraps gst_app_src_get_stream_type
	// The function returns the following values:
	// 
	// 	- goret AppStreamType 
	//
	// Get the stream type. Control the stream type of @appsrc
	// with gst_app_src_set_stream_type().
	GetStreamType() AppStreamType
	// PushBuffer wraps gst_app_src_push_buffer
	// 
	// The function takes the following parameters:
	// 
	// 	- buffer *gst.Buffer: a #GstBuffer to push 
	// 
	// The function returns the following values:
	// 
	// 	- goret gst.FlowReturn 
	//
	// Adds a buffer to the queue of buffers that the appsrc element will
	// push to its source pad.  This function takes ownership of the buffer.
	// 
	// When the block property is TRUE, this function can block until free
	// space becomes available in the queue.
	PushBuffer(*gst.Buffer) gst.FlowReturn
	// PushBufferList wraps gst_app_src_push_buffer_list
	// 
	// The function takes the following parameters:
	// 
	// 	- bufferList *gst.BufferList: a #GstBufferList to push 
	// 
	// The function returns the following values:
	// 
	// 	- goret gst.FlowReturn 
	//
	// Adds a buffer list to the queue of buffers and buffer lists that the
	// appsrc element will push to its source pad.  This function takes ownership
	// of @buffer_list.
	// 
	// When the block property is TRUE, this function can block until free
	// space becomes available in the queue.
	PushBufferList(*gst.BufferList) gst.FlowReturn
	// PushSample wraps gst_app_src_push_sample
	// 
	// The function takes the following parameters:
	// 
	// 	- sample *gst.Sample: a #GstSample from which buffer and caps may be
	// extracted 
	// 
	// The function returns the following values:
	// 
	// 	- goret gst.FlowReturn 
	//
	// Extract a buffer from the provided sample and adds it to the queue of
	// buffers that the appsrc element will push to its source pad. Any
	// previous caps that were set on appsrc will be replaced by the caps
	// associated with the sample if not equal.
	// 
	// This function does not take ownership of the
	// sample so the sample needs to be unreffed after calling this function.
	// 
	// When the block property is TRUE, this function can block until free
	// space becomes available in the queue.
	PushSample(*gst.Sample) gst.FlowReturn
	// AppSrcSetCaps wraps gst_app_src_set_caps
	// 
	// The function takes the following parameters:
	// 
	// 	- caps *gst.Caps (nullable): caps to set 
	//
	// Set the capabilities on the appsrc element.  This function takes
	// a copy of the caps structure. After calling this method, the source will
	// only produce caps that match @caps. @caps must be fixed and the caps on the
	// buffers must match the caps or left NULL.
	AppSrcSetCaps(*gst.Caps)
	// SetDuration wraps gst_app_src_set_duration
	// 
	// The function takes the following parameters:
	// 
	// 	- duration gst.ClockTime: the duration to set 
	//
	// Set the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
	// not known.
	SetDuration(gst.ClockTime)
	// SetEmitSignals wraps gst_app_src_set_emit_signals
	// 
	// The function takes the following parameters:
	// 
	// 	- emit bool: the new state 
	//
	// Make appsrc emit the "new-preroll" and "new-buffer" signals. This option is
	// by default disabled because signal emission is expensive and unneeded when
	// the application prefers to operate in pull mode.
	SetEmitSignals(bool)
	// SetLatency wraps gst_app_src_set_latency
	// 
	// The function takes the following parameters:
	// 
	// 	- min uint64: the min latency 
	// 	- max uint64: the max latency 
	//
	// Configure the @min and @max latency in @src. If @min is set to -1, the
	// default latency calculations for pseudo-live sources will be used.
	SetLatency(uint64, uint64)
	// SetLeakyType wraps gst_app_src_set_leaky_type
	// 
	// The function takes the following parameters:
	// 
	// 	- leaky AppLeakyType: the #GstAppLeakyType 
	//
	// When set to any other value than GST_APP_LEAKY_TYPE_NONE then the appsrc
	// will drop any buffers that are pushed into it once its internal queue is
	// full. The selected type defines whether to drop the oldest or new
	// buffers.
	SetLeakyType(AppLeakyType)
	// SetMaxBuffers wraps gst_app_src_set_max_buffers
	// 
	// The function takes the following parameters:
	// 
	// 	- max uint64: the maximum number of buffers to queue 
	//
	// Set the maximum amount of buffers that can be queued in @appsrc.
	// After the maximum amount of buffers are queued, @appsrc will emit the
	// "enough-data" signal.
	SetMaxBuffers(uint64)
	// SetMaxBytes wraps gst_app_src_set_max_bytes
	// 
	// The function takes the following parameters:
	// 
	// 	- max uint64: the maximum number of bytes to queue 
	//
	// Set the maximum amount of bytes that can be queued in @appsrc.
	// After the maximum amount of bytes are queued, @appsrc will emit the
	// "enough-data" signal.
	SetMaxBytes(uint64)
	// SetMaxTime wraps gst_app_src_set_max_time
	// 
	// The function takes the following parameters:
	// 
	// 	- max gst.ClockTime: the maximum amonut of time to queue 
	//
	// Set the maximum amount of time that can be queued in @appsrc.
	// After the maximum amount of time are queued, @appsrc will emit the
	// "enough-data" signal.
	SetMaxTime(gst.ClockTime)
	// SetSize wraps gst_app_src_set_size
	// 
	// The function takes the following parameters:
	// 
	// 	- size int64: the size to set 
	//
	// Set the size of the stream in bytes. A value of -1 means that the size is
	// not known.
	SetSize(int64)
	// SetStreamType wraps gst_app_src_set_stream_type
	// 
	// The function takes the following parameters:
	// 
	// 	- typ AppStreamType: the new state 
	//
	// Set the stream type on @appsrc. For seekable streams, the "seek" signal must
	// be connected to.
	// 
	// A stream_type stream
	SetStreamType(AppStreamType)
}

func unsafeWrapAppSrc(base *gobject.ObjectInstance) *AppSrcInstance {
	return &AppSrcInstance{
		BaseSrcInstance: gstbase.BaseSrcInstance{
			ElementInstance: gst.ElementInstance{
				ObjectInstance: gst.ObjectInstance{
					InitiallyUnownedInstance: gobject.InitiallyUnownedInstance{
						ObjectInstance: *base,
					},
				},
			},
		},
		URIHandlerInstance: gst.URIHandlerInstance{
			Instance: *base,
		},
	}
}

func marshalAppSrcInstance(p unsafe.Pointer) (any, error) {
	return unsafeWrapAppSrc(gobject.ValueFromNative(p).Object()), nil
}

// UnsafeAppSrcFromGlibNone is used to convert raw GstAppSrc pointers to go while taking a reference and attaching a finalizer. This is used by the bindings internally.
func UnsafeAppSrcFromGlibNone(c unsafe.Pointer) AppSrc {
	return gobject.UnsafeObjectFromGlibNone(c).(AppSrc)
}

// UnsafeAppSrcFromGlibFull is used to convert raw GstAppSrc pointers to go while attaching a finalizer. This is used by the bindings internally.
func UnsafeAppSrcFromGlibFull(c unsafe.Pointer) AppSrc {
	return gobject.UnsafeObjectFromGlibFull(c).(AppSrc)
}

func (a *AppSrcInstance) upcastToGstAppSrc() *AppSrcInstance {
	return a
}

// UnsafeAppSrcToGlibNone is used to convert the instance to it's C value GstAppSrc. This is used by the bindings internally.
func UnsafeAppSrcToGlibNone(c AppSrc) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibNone(c)
}

// UnsafeAppSrcToGlibFull is used to convert the instance to it's C value GstAppSrc, while removeing the finalizer. This is used by the bindings internally.
func UnsafeAppSrcToGlibFull(c AppSrc) unsafe.Pointer {
	return gobject.UnsafeObjectToGlibFull(c)
}

// EndOfStream wraps gst_app_src_end_of_stream
// The function returns the following values:
// 
// 	- goret gst.FlowReturn 
//
// Indicates to the appsrc element that the last buffer queued in the
// element is the last buffer of the stream.
func (appsrc *AppSrcInstance) EndOfStream() gst.FlowReturn {
	var carg0 *C.GstAppSrc    // in, none, converted
	var cret  C.GstFlowReturn // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_end_of_stream(carg0)
	runtime.KeepAlive(appsrc)

	var goret gst.FlowReturn

	goret = gst.FlowReturn(cret)

	return goret
}

// GetCaps wraps gst_app_src_get_caps
// The function returns the following values:
// 
// 	- goret *gst.Caps 
//
// Get the configured caps on @appsrc.
func (appsrc *AppSrcInstance) GetCaps() *gst.Caps {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  *C.GstCaps   // return, full, converted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_caps(carg0)
	runtime.KeepAlive(appsrc)

	var goret *gst.Caps

	goret = gst.UnsafeCapsFromGlibFull(unsafe.Pointer(cret))

	return goret
}

// GetCurrentLevelBuffers wraps gst_app_src_get_current_level_buffers
// The function returns the following values:
// 
// 	- goret uint64 
//
// Get the number of currently queued buffers inside @appsrc.
func (appsrc *AppSrcInstance) GetCurrentLevelBuffers() uint64 {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.guint64    // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_current_level_buffers(carg0)
	runtime.KeepAlive(appsrc)

	var goret uint64

	goret = uint64(cret)

	return goret
}

// GetCurrentLevelBytes wraps gst_app_src_get_current_level_bytes
// The function returns the following values:
// 
// 	- goret uint64 
//
// Get the number of currently queued bytes inside @appsrc.
func (appsrc *AppSrcInstance) GetCurrentLevelBytes() uint64 {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.guint64    // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_current_level_bytes(carg0)
	runtime.KeepAlive(appsrc)

	var goret uint64

	goret = uint64(cret)

	return goret
}

// GetCurrentLevelTime wraps gst_app_src_get_current_level_time
// The function returns the following values:
// 
// 	- goret gst.ClockTime 
//
// Get the amount of currently queued time inside @appsrc.
func (appsrc *AppSrcInstance) GetCurrentLevelTime() gst.ClockTime {
	var carg0 *C.GstAppSrc   // in, none, converted
	var cret  C.GstClockTime // return, none, casted, alias

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_current_level_time(carg0)
	runtime.KeepAlive(appsrc)

	var goret gst.ClockTime

	goret = gst.ClockTime(cret)

	return goret
}

// GetDuration wraps gst_app_src_get_duration
// The function returns the following values:
// 
// 	- goret gst.ClockTime 
//
// Get the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
// not known.
func (appsrc *AppSrcInstance) GetDuration() gst.ClockTime {
	var carg0 *C.GstAppSrc   // in, none, converted
	var cret  C.GstClockTime // return, none, casted, alias

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_duration(carg0)
	runtime.KeepAlive(appsrc)

	var goret gst.ClockTime

	goret = gst.ClockTime(cret)

	return goret
}

// GetEmitSignals wraps gst_app_src_get_emit_signals
// The function returns the following values:
// 
// 	- goret bool 
//
// Check if appsrc will emit the "new-preroll" and "new-buffer" signals.
func (appsrc *AppSrcInstance) GetEmitSignals() bool {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.gboolean   // return

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_emit_signals(carg0)
	runtime.KeepAlive(appsrc)

	var goret bool

	if cret != 0 {
		goret = true
	}

	return goret
}

// GetLatency wraps gst_app_src_get_latency
// The function returns the following values:
// 
// 	- min uint64: the min latency 
// 	- max uint64: the max latency 
//
// Retrieve the min and max latencies in @min and @max respectively.
func (appsrc *AppSrcInstance) GetLatency() (uint64, uint64) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.guint64    // out, full, casted
	var carg2 C.guint64    // out, full, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	C.gst_app_src_get_latency(carg0, &carg1, &carg2)
	runtime.KeepAlive(appsrc)

	var min uint64
	var max uint64

	min = uint64(carg1)
	max = uint64(carg2)

	return min, max
}

// GetLeakyType wraps gst_app_src_get_leaky_type
// The function returns the following values:
// 
// 	- goret AppLeakyType 
//
// Returns the currently set #GstAppLeakyType. See gst_app_src_set_leaky_type()
// for more details.
func (appsrc *AppSrcInstance) GetLeakyType() AppLeakyType {
	var carg0 *C.GstAppSrc      // in, none, converted
	var cret  C.GstAppLeakyType // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_leaky_type(carg0)
	runtime.KeepAlive(appsrc)

	var goret AppLeakyType

	goret = AppLeakyType(cret)

	return goret
}

// GetMaxBuffers wraps gst_app_src_get_max_buffers
// The function returns the following values:
// 
// 	- goret uint64 
//
// Get the maximum amount of buffers that can be queued in @appsrc.
func (appsrc *AppSrcInstance) GetMaxBuffers() uint64 {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.guint64    // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_max_buffers(carg0)
	runtime.KeepAlive(appsrc)

	var goret uint64

	goret = uint64(cret)

	return goret
}

// GetMaxBytes wraps gst_app_src_get_max_bytes
// The function returns the following values:
// 
// 	- goret uint64 
//
// Get the maximum amount of bytes that can be queued in @appsrc.
func (appsrc *AppSrcInstance) GetMaxBytes() uint64 {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.guint64    // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_max_bytes(carg0)
	runtime.KeepAlive(appsrc)

	var goret uint64

	goret = uint64(cret)

	return goret
}

// GetMaxTime wraps gst_app_src_get_max_time
// The function returns the following values:
// 
// 	- goret gst.ClockTime 
//
// Get the maximum amount of time that can be queued in @appsrc.
func (appsrc *AppSrcInstance) GetMaxTime() gst.ClockTime {
	var carg0 *C.GstAppSrc   // in, none, converted
	var cret  C.GstClockTime // return, none, casted, alias

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_max_time(carg0)
	runtime.KeepAlive(appsrc)

	var goret gst.ClockTime

	goret = gst.ClockTime(cret)

	return goret
}

// GetSize wraps gst_app_src_get_size
// The function returns the following values:
// 
// 	- goret int64 
//
// Get the size of the stream in bytes. A value of -1 means that the size is
// not known.
func (appsrc *AppSrcInstance) GetSize() int64 {
	var carg0 *C.GstAppSrc // in, none, converted
	var cret  C.gint64     // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_size(carg0)
	runtime.KeepAlive(appsrc)

	var goret int64

	goret = int64(cret)

	return goret
}

// GetStreamType wraps gst_app_src_get_stream_type
// The function returns the following values:
// 
// 	- goret AppStreamType 
//
// Get the stream type. Control the stream type of @appsrc
// with gst_app_src_set_stream_type().
func (appsrc *AppSrcInstance) GetStreamType() AppStreamType {
	var carg0 *C.GstAppSrc       // in, none, converted
	var cret  C.GstAppStreamType // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))

	cret = C.gst_app_src_get_stream_type(carg0)
	runtime.KeepAlive(appsrc)

	var goret AppStreamType

	goret = AppStreamType(cret)

	return goret
}

// PushBuffer wraps gst_app_src_push_buffer
// 
// The function takes the following parameters:
// 
// 	- buffer *gst.Buffer: a #GstBuffer to push 
// 
// The function returns the following values:
// 
// 	- goret gst.FlowReturn 
//
// Adds a buffer to the queue of buffers that the appsrc element will
// push to its source pad.  This function takes ownership of the buffer.
// 
// When the block property is TRUE, this function can block until free
// space becomes available in the queue.
func (appsrc *AppSrcInstance) PushBuffer(buffer *gst.Buffer) gst.FlowReturn {
	var carg0 *C.GstAppSrc    // in, none, converted
	var carg1 *C.GstBuffer    // in, full, converted
	var cret  C.GstFlowReturn // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = (*C.GstBuffer)(gst.UnsafeBufferToGlibFull(buffer))

	cret = C.gst_app_src_push_buffer(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(buffer)

	var goret gst.FlowReturn

	goret = gst.FlowReturn(cret)

	return goret
}

// PushBufferList wraps gst_app_src_push_buffer_list
// 
// The function takes the following parameters:
// 
// 	- bufferList *gst.BufferList: a #GstBufferList to push 
// 
// The function returns the following values:
// 
// 	- goret gst.FlowReturn 
//
// Adds a buffer list to the queue of buffers and buffer lists that the
// appsrc element will push to its source pad.  This function takes ownership
// of @buffer_list.
// 
// When the block property is TRUE, this function can block until free
// space becomes available in the queue.
func (appsrc *AppSrcInstance) PushBufferList(bufferList *gst.BufferList) gst.FlowReturn {
	var carg0 *C.GstAppSrc     // in, none, converted
	var carg1 *C.GstBufferList // in, full, converted
	var cret  C.GstFlowReturn  // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = (*C.GstBufferList)(gst.UnsafeBufferListToGlibFull(bufferList))

	cret = C.gst_app_src_push_buffer_list(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(bufferList)

	var goret gst.FlowReturn

	goret = gst.FlowReturn(cret)

	return goret
}

// PushSample wraps gst_app_src_push_sample
// 
// The function takes the following parameters:
// 
// 	- sample *gst.Sample: a #GstSample from which buffer and caps may be
// extracted 
// 
// The function returns the following values:
// 
// 	- goret gst.FlowReturn 
//
// Extract a buffer from the provided sample and adds it to the queue of
// buffers that the appsrc element will push to its source pad. Any
// previous caps that were set on appsrc will be replaced by the caps
// associated with the sample if not equal.
// 
// This function does not take ownership of the
// sample so the sample needs to be unreffed after calling this function.
// 
// When the block property is TRUE, this function can block until free
// space becomes available in the queue.
func (appsrc *AppSrcInstance) PushSample(sample *gst.Sample) gst.FlowReturn {
	var carg0 *C.GstAppSrc    // in, none, converted
	var carg1 *C.GstSample    // in, none, converted
	var cret  C.GstFlowReturn // return, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = (*C.GstSample)(gst.UnsafeSampleToGlibNone(sample))

	cret = C.gst_app_src_push_sample(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(sample)

	var goret gst.FlowReturn

	goret = gst.FlowReturn(cret)

	return goret
}

// AppSrcSetCaps wraps gst_app_src_set_caps
// 
// The function takes the following parameters:
// 
// 	- caps *gst.Caps (nullable): caps to set 
//
// Set the capabilities on the appsrc element.  This function takes
// a copy of the caps structure. After calling this method, the source will
// only produce caps that match @caps. @caps must be fixed and the caps on the
// buffers must match the caps or left NULL.
func (appsrc *AppSrcInstance) AppSrcSetCaps(caps *gst.Caps) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 *C.GstCaps   // in, none, converted, nullable

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	if caps != nil {
		carg1 = (*C.GstCaps)(gst.UnsafeCapsToGlibNone(caps))
	}

	C.gst_app_src_set_caps(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(caps)
}

// SetDuration wraps gst_app_src_set_duration
// 
// The function takes the following parameters:
// 
// 	- duration gst.ClockTime: the duration to set 
//
// Set the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
// not known.
func (appsrc *AppSrcInstance) SetDuration(duration gst.ClockTime) {
	var carg0 *C.GstAppSrc   // in, none, converted
	var carg1 C.GstClockTime // in, none, casted, alias

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.GstClockTime(duration)

	C.gst_app_src_set_duration(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(duration)
}

// SetEmitSignals wraps gst_app_src_set_emit_signals
// 
// The function takes the following parameters:
// 
// 	- emit bool: the new state 
//
// Make appsrc emit the "new-preroll" and "new-buffer" signals. This option is
// by default disabled because signal emission is expensive and unneeded when
// the application prefers to operate in pull mode.
func (appsrc *AppSrcInstance) SetEmitSignals(emit bool) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.gboolean   // in

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	if emit {
		carg1 = C.TRUE
	}

	C.gst_app_src_set_emit_signals(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(emit)
}

// SetLatency wraps gst_app_src_set_latency
// 
// The function takes the following parameters:
// 
// 	- min uint64: the min latency 
// 	- max uint64: the max latency 
//
// Configure the @min and @max latency in @src. If @min is set to -1, the
// default latency calculations for pseudo-live sources will be used.
func (appsrc *AppSrcInstance) SetLatency(min uint64, max uint64) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.guint64    // in, none, casted
	var carg2 C.guint64    // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.guint64(min)
	carg2 = C.guint64(max)

	C.gst_app_src_set_latency(carg0, carg1, carg2)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(min)
	runtime.KeepAlive(max)
}

// SetLeakyType wraps gst_app_src_set_leaky_type
// 
// The function takes the following parameters:
// 
// 	- leaky AppLeakyType: the #GstAppLeakyType 
//
// When set to any other value than GST_APP_LEAKY_TYPE_NONE then the appsrc
// will drop any buffers that are pushed into it once its internal queue is
// full. The selected type defines whether to drop the oldest or new
// buffers.
func (appsrc *AppSrcInstance) SetLeakyType(leaky AppLeakyType) {
	var carg0 *C.GstAppSrc      // in, none, converted
	var carg1 C.GstAppLeakyType // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.GstAppLeakyType(leaky)

	C.gst_app_src_set_leaky_type(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(leaky)
}

// SetMaxBuffers wraps gst_app_src_set_max_buffers
// 
// The function takes the following parameters:
// 
// 	- max uint64: the maximum number of buffers to queue 
//
// Set the maximum amount of buffers that can be queued in @appsrc.
// After the maximum amount of buffers are queued, @appsrc will emit the
// "enough-data" signal.
func (appsrc *AppSrcInstance) SetMaxBuffers(max uint64) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.guint64    // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.guint64(max)

	C.gst_app_src_set_max_buffers(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(max)
}

// SetMaxBytes wraps gst_app_src_set_max_bytes
// 
// The function takes the following parameters:
// 
// 	- max uint64: the maximum number of bytes to queue 
//
// Set the maximum amount of bytes that can be queued in @appsrc.
// After the maximum amount of bytes are queued, @appsrc will emit the
// "enough-data" signal.
func (appsrc *AppSrcInstance) SetMaxBytes(max uint64) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.guint64    // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.guint64(max)

	C.gst_app_src_set_max_bytes(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(max)
}

// SetMaxTime wraps gst_app_src_set_max_time
// 
// The function takes the following parameters:
// 
// 	- max gst.ClockTime: the maximum amonut of time to queue 
//
// Set the maximum amount of time that can be queued in @appsrc.
// After the maximum amount of time are queued, @appsrc will emit the
// "enough-data" signal.
func (appsrc *AppSrcInstance) SetMaxTime(max gst.ClockTime) {
	var carg0 *C.GstAppSrc   // in, none, converted
	var carg1 C.GstClockTime // in, none, casted, alias

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.GstClockTime(max)

	C.gst_app_src_set_max_time(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(max)
}

// SetSize wraps gst_app_src_set_size
// 
// The function takes the following parameters:
// 
// 	- size int64: the size to set 
//
// Set the size of the stream in bytes. A value of -1 means that the size is
// not known.
func (appsrc *AppSrcInstance) SetSize(size int64) {
	var carg0 *C.GstAppSrc // in, none, converted
	var carg1 C.gint64     // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.gint64(size)

	C.gst_app_src_set_size(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(size)
}

// SetStreamType wraps gst_app_src_set_stream_type
// 
// The function takes the following parameters:
// 
// 	- typ AppStreamType: the new state 
//
// Set the stream type on @appsrc. For seekable streams, the "seek" signal must
// be connected to.
// 
// A stream_type stream
func (appsrc *AppSrcInstance) SetStreamType(typ AppStreamType) {
	var carg0 *C.GstAppSrc       // in, none, converted
	var carg1 C.GstAppStreamType // in, none, casted

	carg0 = (*C.GstAppSrc)(UnsafeAppSrcToGlibNone(appsrc))
	carg1 = C.GstAppStreamType(typ)

	C.gst_app_src_set_stream_type(carg0, carg1)
	runtime.KeepAlive(appsrc)
	runtime.KeepAlive(typ)
}

// AppSinkClass wraps GstAppSinkClass
type AppSinkClass struct {
	*appSinkClass
}

// appSinkClass is the struct that's finalized
type appSinkClass struct {
	native *C.GstAppSinkClass
}

// UnsafeAppSinkClassFromGlibBorrow is used to convert raw C.GstAppSinkClass pointers to go. This is used by the bindings internally.
func UnsafeAppSinkClassFromGlibBorrow(p unsafe.Pointer) *AppSinkClass {
	return &AppSinkClass{&appSinkClass{(*C.GstAppSinkClass)(p)}}
}

// UnsafeAppSinkClassFromGlibNone is used to convert raw C.GstAppSinkClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeAppSinkClassFromGlibNone(p unsafe.Pointer) *AppSinkClass {
	// FIXME: this has no ref function, what should we do here?
	wrapped := UnsafeAppSinkClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.appSinkClass,
		func (intern *appSinkClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeAppSinkClassFromGlibFull is used to convert raw C.GstAppSinkClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeAppSinkClassFromGlibFull(p unsafe.Pointer) *AppSinkClass {
	wrapped := UnsafeAppSinkClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.appSinkClass,
		func (intern *appSinkClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeAppSinkClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [AppSinkClass] is expected to work anymore.
func UnsafeAppSinkClassFree(a *AppSinkClass) {
	C.free(unsafe.Pointer(a.native))
}

// UnsafeAppSinkClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeAppSinkClassToGlibNone(a *AppSinkClass) unsafe.Pointer {
	return unsafe.Pointer(a.native)
}

// UnsafeAppSinkClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeAppSinkClassToGlibFull(a *AppSinkClass) unsafe.Pointer {
	runtime.SetFinalizer(a.appSinkClass, nil)
	_p := unsafe.Pointer(a.native)
	a.native = nil // AppSinkClass is invalid from here on
	return _p
}
// AppSrcClass wraps GstAppSrcClass
type AppSrcClass struct {
	*appSrcClass
}

// appSrcClass is the struct that's finalized
type appSrcClass struct {
	native *C.GstAppSrcClass
}

// UnsafeAppSrcClassFromGlibBorrow is used to convert raw C.GstAppSrcClass pointers to go. This is used by the bindings internally.
func UnsafeAppSrcClassFromGlibBorrow(p unsafe.Pointer) *AppSrcClass {
	return &AppSrcClass{&appSrcClass{(*C.GstAppSrcClass)(p)}}
}

// UnsafeAppSrcClassFromGlibNone is used to convert raw C.GstAppSrcClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeAppSrcClassFromGlibNone(p unsafe.Pointer) *AppSrcClass {
	// FIXME: this has no ref function, what should we do here?
	wrapped := UnsafeAppSrcClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.appSrcClass,
		func (intern *appSrcClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeAppSrcClassFromGlibFull is used to convert raw C.GstAppSrcClass pointers to go while taking a reference. This is used by the bindings internally.
func UnsafeAppSrcClassFromGlibFull(p unsafe.Pointer) *AppSrcClass {
	wrapped := UnsafeAppSrcClassFromGlibBorrow(p)
	runtime.SetFinalizer(
		wrapped.appSrcClass,
		func (intern *appSrcClass) {
			C.free(unsafe.Pointer(intern.native))
		},
	)
	return wrapped
}

// UnsafeAppSrcClassFree unrefs/frees the underlying resource. This is used by the bindings internally.
// 
// After this is called, no other method on [AppSrcClass] is expected to work anymore.
func UnsafeAppSrcClassFree(a *AppSrcClass) {
	C.free(unsafe.Pointer(a.native))
}

// UnsafeAppSrcClassToGlibNone returns the underlying C pointer. This is used by the bindings internally.
func UnsafeAppSrcClassToGlibNone(a *AppSrcClass) unsafe.Pointer {
	return unsafe.Pointer(a.native)
}

// UnsafeAppSrcClassToGlibFull returns the underlying C pointer and gives up ownership.
// This is used by the bindings internally.
func UnsafeAppSrcClassToGlibFull(a *AppSrcClass) unsafe.Pointer {
	runtime.SetFinalizer(a.appSrcClass, nil)
	_p := unsafe.Pointer(a.native)
	a.native = nil // AppSrcClass is invalid from here on
	return _p
}
