#!/usr/bin/env bash

find . -type f -name "*.go" ! -name "*_deprecation.go" | while read file; do
    awk '
    /^[^ \t]/ { # Only consider global (non-indented) lines
        if ($1 == "func" || ($1 == "type" && ($3 == "struct" || $3 == "interface"))) {
            print "//\n// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead."
        }
    }
    { print }
    ' "$file" >"$file.tmp" && mv "$file.tmp" "$file"
done
