// Code generated by girgen for GstRtsp-1. DO NOT EDIT.

package gstrtsp

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/userdata"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
)

// #include <gst/rtsp/rtsp.h>
import "C"

//export _gotk4_gstrtsp1_RTSPConnectionAcceptCertificateFunc
func _gotk4_gstrtsp1_RTSPConnectionAcceptCertificateFunc(carg1 *C.GTlsConnection, carg2 *C.GTlsCertificate, carg3 C.GTlsCertificateFlags, carg4 C.gpointer) (cret C.gboolean) {
	var fn RTSPConnectionAcceptCertificateFunc
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(RTSPConnectionAcceptCertificateFunc)
	}

	var conn     gio.TlsConnection       // in, none, converted
	var peerCert gio.TlsCertificate      // in, none, converted
	var errors   gio.TLSCertificateFlags // in, none, casted
	var goret    bool                    // return

	conn = gio.UnsafeTlsConnectionFromGlibNone(unsafe.Pointer(carg1))
	peerCert = gio.UnsafeTlsCertificateFromGlibNone(unsafe.Pointer(carg2))
	errors = gio.TLSCertificateFlags(carg3)

	goret = fn(conn, peerCert, errors)

	if goret {
		cret = C.TRUE
	}

	return cret
}

//export _gotk4_gstrtsp1_RTSPExtension_after_send
func _gotk4_gstrtsp1_RTSPExtension_after_send(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPMessage, carg2 *C.GstRTSPMessage) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_before_send
func _gotk4_gstrtsp1_RTSPExtension_before_send(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPMessage) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_configure_stream
func _gotk4_gstrtsp1_RTSPExtension_configure_stream(carg0 *C.GstRTSPExtension, carg1 *C.GstCaps) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_detect_server
func _gotk4_gstrtsp1_RTSPExtension_detect_server(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPMessage) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_parse_sdp
func _gotk4_gstrtsp1_RTSPExtension_parse_sdp(carg0 *C.GstRTSPExtension, carg1 *C.GstSDPMessage, carg2 *C.GstStructure) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_receive_request
func _gotk4_gstrtsp1_RTSPExtension_receive_request(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPMessage) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_send
func _gotk4_gstrtsp1_RTSPExtension_send(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPMessage, carg2 *C.GstRTSPMessage) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_setup_media
func _gotk4_gstrtsp1_RTSPExtension_setup_media(carg0 *C.GstRTSPExtension, carg1 *C.GstSDPMedia) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

//export _gotk4_gstrtsp1_RTSPExtension_stream_select
func _gotk4_gstrtsp1_RTSPExtension_stream_select(carg0 *C.GstRTSPExtension, carg1 *C.GstRTSPUrl) (cret C.GstRTSPResult) {
	panic("unimplemented")
}

