// Code generated by girgen. DO NOT EDIT.

package gstaudio

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/userdata"
	"github.com/go-gst/go-gst/pkg/gst"
)

// #include <gst/audio/audio.h>
import "C"

//export _gotk4_gstaudio1_AudioBaseSinkCustomSlavingCallback
func _gotk4_gstaudio1_AudioBaseSinkCustomSlavingCallback(carg1 *C.GstAudioBaseSink, carg2 C.GstClockTime, carg3 C.GstClockTime, carg4 *C.GstClockTimeDiff, carg5 C.GstAudioBaseSinkDiscontReason, carg6 C.gpointer) {
	var fn AudioBaseSinkCustomSlavingCallback
	{
		v := userdata.Load(unsafe.Pointer(carg6))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioBaseSinkCustomSlavingCallback)
	}

	var sink          AudioBaseSink              // in, none, converted
	var etime         gst.ClockTime              // in, none, casted, alias
	var itime         gst.ClockTime              // in, none, casted, alias
	var requestedSkew *gst.ClockTimeDiff         // in, transfer: none, C Pointers: 1, Name: ClockTimeDiff
	var discontReason AudioBaseSinkDiscontReason // in, none, casted

	sink = UnsafeAudioBaseSinkFromGlibNone(unsafe.Pointer(carg1))
	etime = gst.ClockTime(carg2)
	itime = gst.ClockTime(carg3)
	_ = requestedSkew
	_ = carg4
	panic("unimplemented conversion of *gst.ClockTimeDiff (GstClockTimeDiff*)")
	discontReason = AudioBaseSinkDiscontReason(carg5)

	fn(sink, etime, itime, requestedSkew, discontReason)
}

//export _gotk4_gstaudio1_AudioClockGetTimeFunc
func _gotk4_gstaudio1_AudioClockGetTimeFunc(carg1 *C.GstClock, carg2 C.gpointer) (cret C.GstClockTime) {
	var fn AudioClockGetTimeFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioClockGetTimeFunc)
	}

	var clock gst.Clock     // in, none, converted
	var goret gst.ClockTime // return, none, casted, alias

	clock = gst.UnsafeClockFromGlibNone(unsafe.Pointer(carg1))

	goret = fn(clock)

	cret = C.GstClockTime(goret)

	return cret
}

//export _gotk4_gstaudio1_AudioRingBufferCallback
func _gotk4_gstaudio1_AudioRingBufferCallback(carg1 *C.GstAudioRingBuffer, carg2 *C.guint8, carg3 C.guint, carg4 C.gpointer) {
	var fn AudioRingBufferCallback
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioRingBufferCallback)
	}

	var rbuf AudioRingBuffer // in, none, converted
	var data []uint8         // in, transfer: none, C Pointers: 1, Name: array[guint8], array (inner: *typesystem.CastablePrimitive, length-by: carg3)

	rbuf = UnsafeAudioRingBufferFromGlibNone(unsafe.Pointer(carg1))
	_ = data
	_ = carg2
	_ = carg3
	panic("unimplemented conversion of []uint8 (guint8*)")

	fn(rbuf, data)
}

