// Code generated by girgen for GstAudio-1. DO NOT EDIT.

package gstaudio

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/userdata"
	"github.com/go-gst/go-gst/pkg/gst"
)

// #include <gst/audio/audio.h>
import "C"

//export _gotk4_gstaudio1_AudioBaseSinkCustomSlavingCallback
func _gotk4_gstaudio1_AudioBaseSinkCustomSlavingCallback(carg1 *C.GstAudioBaseSink, carg2 C.GstClockTime, carg3 C.GstClockTime, carg4 *C.GstClockTimeDiff, carg5 C.GstAudioBaseSinkDiscontReason, carg6 C.gpointer) {
	var fn AudioBaseSinkCustomSlavingCallback
	{
		v := userdata.Load(unsafe.Pointer(carg6))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioBaseSinkCustomSlavingCallback)
	}

	var sink          AudioBaseSink              // in, none, converted
	var etime         gst.ClockTime              // in, none, casted, alias
	var itime         gst.ClockTime              // in, none, casted, alias
	var requestedSkew *gst.ClockTimeDiff         // in, transfer: none, C Pointers: 1, Name: ClockTimeDiff
	var discontReason AudioBaseSinkDiscontReason // in, none, casted

	sink = UnsafeAudioBaseSinkFromGlibNone(unsafe.Pointer(carg1))
	etime = gst.ClockTime(carg2)
	itime = gst.ClockTime(carg3)
	_ = requestedSkew
	_ = carg4
	panic("unimplemented conversion of *gst.ClockTimeDiff (GstClockTimeDiff*)")
	discontReason = AudioBaseSinkDiscontReason(carg5)

	fn(sink, etime, itime, requestedSkew, discontReason)
}

//export _gotk4_gstaudio1_AudioClockGetTimeFunc
func _gotk4_gstaudio1_AudioClockGetTimeFunc(carg1 *C.GstClock, carg2 C.gpointer) (cret C.GstClockTime) {
	var fn AudioClockGetTimeFunc
	{
		v := userdata.Load(unsafe.Pointer(carg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioClockGetTimeFunc)
	}

	var clock gst.Clock     // in, none, converted
	var goret gst.ClockTime // return, none, casted, alias

	clock = gst.UnsafeClockFromGlibNone(unsafe.Pointer(carg1))

	goret = fn(clock)

	cret = C.GstClockTime(goret)

	return cret
}

//export _gotk4_gstaudio1_AudioRingBufferCallback
func _gotk4_gstaudio1_AudioRingBufferCallback(carg1 *C.GstAudioRingBuffer, carg2 *C.guint8, carg3 C.guint, carg4 C.gpointer) {
	var fn AudioRingBufferCallback
	{
		v := userdata.Load(unsafe.Pointer(carg4))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AudioRingBufferCallback)
	}

	var rbuf AudioRingBuffer // in, none, converted
	var data []uint8         // in, transfer: none, C Pointers: 1, Name: array[guint8], array (inner: *typesystem.CastablePrimitive, length-by: carg3)

	rbuf = UnsafeAudioRingBufferFromGlibNone(unsafe.Pointer(carg1))
	_ = data
	_ = carg2
	_ = carg3
	panic("unimplemented conversion of []uint8 (guint8*)")

	fn(rbuf, data)
}

//export _gotk4_gstaudio1_AudioAggregator_aggregate_one_buffer
func _gotk4_gstaudio1_AudioAggregator_aggregate_one_buffer(carg0 *C.GstAudioAggregator, carg1 *C.GstAudioAggregatorPad, carg2 *C.GstBuffer, carg3 C.guint, carg4 *C.GstBuffer, carg5 C.guint, carg6 C.guint) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioAggregator_create_output_buffer
func _gotk4_gstaudio1_AudioAggregator_create_output_buffer(carg0 *C.GstAudioAggregator, carg1 C.guint) (cret *C.GstBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioAggregatorPad_convert_buffer
func _gotk4_gstaudio1_AudioAggregatorPad_convert_buffer(carg0 *C.GstAudioAggregatorPad, carg1 *C.GstAudioInfo, carg2 *C.GstAudioInfo, carg3 *C.GstBuffer) (cret *C.GstBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioAggregatorPad_update_conversion_info
func _gotk4_gstaudio1_AudioAggregatorPad_update_conversion_info(carg0 *C.GstAudioAggregatorPad) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioBaseSink_create_ringbuffer
func _gotk4_gstaudio1_AudioBaseSink_create_ringbuffer(carg0 *C.GstAudioBaseSink) (cret *C.GstAudioRingBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioBaseSink_payload
func _gotk4_gstaudio1_AudioBaseSink_payload(carg0 *C.GstAudioBaseSink, carg1 *C.GstBuffer) (cret *C.GstBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioBaseSrc_create_ringbuffer
func _gotk4_gstaudio1_AudioBaseSrc_create_ringbuffer(carg0 *C.GstAudioBaseSrc) (cret *C.GstAudioRingBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioCdSrc_close
func _gotk4_gstaudio1_AudioCdSrc_close(carg0 *C.GstAudioCdSrc) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioCdSrc_open
func _gotk4_gstaudio1_AudioCdSrc_open(carg0 *C.GstAudioCdSrc, carg1 *C.gchar) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioCdSrc_read_sector
func _gotk4_gstaudio1_AudioCdSrc_read_sector(carg0 *C.GstAudioCdSrc, carg1 C.gint) (cret *C.GstBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_close
func _gotk4_gstaudio1_AudioDecoder_close(carg0 *C.GstAudioDecoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_decide_allocation
func _gotk4_gstaudio1_AudioDecoder_decide_allocation(carg0 *C.GstAudioDecoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_flush
func _gotk4_gstaudio1_AudioDecoder_flush(carg0 *C.GstAudioDecoder, carg1 C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_getcaps
func _gotk4_gstaudio1_AudioDecoder_getcaps(carg0 *C.GstAudioDecoder, carg1 *C.GstCaps) (cret *C.GstCaps) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_handle_frame
func _gotk4_gstaudio1_AudioDecoder_handle_frame(carg0 *C.GstAudioDecoder, carg1 *C.GstBuffer) (cret C.GstFlowReturn) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_negotiate
func _gotk4_gstaudio1_AudioDecoder_negotiate(carg0 *C.GstAudioDecoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_open
func _gotk4_gstaudio1_AudioDecoder_open(carg0 *C.GstAudioDecoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_parse
func _gotk4_gstaudio1_AudioDecoder_parse(carg0 *C.GstAudioDecoder, carg1 *C.GstAdapter, carg2 *C.gint, carg3 *C.gint) (cret C.GstFlowReturn) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_propose_allocation
func _gotk4_gstaudio1_AudioDecoder_propose_allocation(carg0 *C.GstAudioDecoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_set_format
func _gotk4_gstaudio1_AudioDecoder_set_format(carg0 *C.GstAudioDecoder, carg1 *C.GstCaps) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_sink_event
func _gotk4_gstaudio1_AudioDecoder_sink_event(carg0 *C.GstAudioDecoder, carg1 *C.GstEvent) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_sink_query
func _gotk4_gstaudio1_AudioDecoder_sink_query(carg0 *C.GstAudioDecoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_src_event
func _gotk4_gstaudio1_AudioDecoder_src_event(carg0 *C.GstAudioDecoder, carg1 *C.GstEvent) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_src_query
func _gotk4_gstaudio1_AudioDecoder_src_query(carg0 *C.GstAudioDecoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_start
func _gotk4_gstaudio1_AudioDecoder_start(carg0 *C.GstAudioDecoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_stop
func _gotk4_gstaudio1_AudioDecoder_stop(carg0 *C.GstAudioDecoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioDecoder_transform_meta
func _gotk4_gstaudio1_AudioDecoder_transform_meta(carg0 *C.GstAudioDecoder, carg1 *C.GstBuffer, carg2 *C.GstMeta, carg3 *C.GstBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_close
func _gotk4_gstaudio1_AudioEncoder_close(carg0 *C.GstAudioEncoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_decide_allocation
func _gotk4_gstaudio1_AudioEncoder_decide_allocation(carg0 *C.GstAudioEncoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_flush
func _gotk4_gstaudio1_AudioEncoder_flush(carg0 *C.GstAudioEncoder) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_getcaps
func _gotk4_gstaudio1_AudioEncoder_getcaps(carg0 *C.GstAudioEncoder, carg1 *C.GstCaps) (cret *C.GstCaps) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_handle_frame
func _gotk4_gstaudio1_AudioEncoder_handle_frame(carg0 *C.GstAudioEncoder, carg1 *C.GstBuffer) (cret C.GstFlowReturn) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_negotiate
func _gotk4_gstaudio1_AudioEncoder_negotiate(carg0 *C.GstAudioEncoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_open
func _gotk4_gstaudio1_AudioEncoder_open(carg0 *C.GstAudioEncoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_propose_allocation
func _gotk4_gstaudio1_AudioEncoder_propose_allocation(carg0 *C.GstAudioEncoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_set_format
func _gotk4_gstaudio1_AudioEncoder_set_format(carg0 *C.GstAudioEncoder, carg1 *C.GstAudioInfo) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_sink_event
func _gotk4_gstaudio1_AudioEncoder_sink_event(carg0 *C.GstAudioEncoder, carg1 *C.GstEvent) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_sink_query
func _gotk4_gstaudio1_AudioEncoder_sink_query(carg0 *C.GstAudioEncoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_src_event
func _gotk4_gstaudio1_AudioEncoder_src_event(carg0 *C.GstAudioEncoder, carg1 *C.GstEvent) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_src_query
func _gotk4_gstaudio1_AudioEncoder_src_query(carg0 *C.GstAudioEncoder, carg1 *C.GstQuery) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_start
func _gotk4_gstaudio1_AudioEncoder_start(carg0 *C.GstAudioEncoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_stop
func _gotk4_gstaudio1_AudioEncoder_stop(carg0 *C.GstAudioEncoder) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioEncoder_transform_meta
func _gotk4_gstaudio1_AudioEncoder_transform_meta(carg0 *C.GstAudioEncoder, carg1 *C.GstBuffer, carg2 *C.GstMeta, carg3 *C.GstBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioFilter_setup
func _gotk4_gstaudio1_AudioFilter_setup(carg0 *C.GstAudioFilter, carg1 *C.GstAudioInfo) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_acquire
func _gotk4_gstaudio1_AudioRingBuffer_acquire(carg0 *C.GstAudioRingBuffer, carg1 *C.GstAudioRingBufferSpec) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_activate
func _gotk4_gstaudio1_AudioRingBuffer_activate(carg0 *C.GstAudioRingBuffer, carg1 C.gboolean) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_clear_all
func _gotk4_gstaudio1_AudioRingBuffer_clear_all(carg0 *C.GstAudioRingBuffer) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_close_device
func _gotk4_gstaudio1_AudioRingBuffer_close_device(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_delay
func _gotk4_gstaudio1_AudioRingBuffer_delay(carg0 *C.GstAudioRingBuffer) (cret C.guint) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_open_device
func _gotk4_gstaudio1_AudioRingBuffer_open_device(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_pause
func _gotk4_gstaudio1_AudioRingBuffer_pause(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_release
func _gotk4_gstaudio1_AudioRingBuffer_release(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_resume
func _gotk4_gstaudio1_AudioRingBuffer_resume(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_start
func _gotk4_gstaudio1_AudioRingBuffer_start(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioRingBuffer_stop
func _gotk4_gstaudio1_AudioRingBuffer_stop(carg0 *C.GstAudioRingBuffer) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_close
func _gotk4_gstaudio1_AudioSink_close(carg0 *C.GstAudioSink) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_delay
func _gotk4_gstaudio1_AudioSink_delay(carg0 *C.GstAudioSink) (cret C.guint) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_open
func _gotk4_gstaudio1_AudioSink_open(carg0 *C.GstAudioSink) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_pause
func _gotk4_gstaudio1_AudioSink_pause(carg0 *C.GstAudioSink) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_prepare
func _gotk4_gstaudio1_AudioSink_prepare(carg0 *C.GstAudioSink, carg1 *C.GstAudioRingBufferSpec) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_reset
func _gotk4_gstaudio1_AudioSink_reset(carg0 *C.GstAudioSink) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_resume
func _gotk4_gstaudio1_AudioSink_resume(carg0 *C.GstAudioSink) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_stop
func _gotk4_gstaudio1_AudioSink_stop(carg0 *C.GstAudioSink) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSink_unprepare
func _gotk4_gstaudio1_AudioSink_unprepare(carg0 *C.GstAudioSink) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_close
func _gotk4_gstaudio1_AudioSrc_close(carg0 *C.GstAudioSrc) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_delay
func _gotk4_gstaudio1_AudioSrc_delay(carg0 *C.GstAudioSrc) (cret C.guint) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_open
func _gotk4_gstaudio1_AudioSrc_open(carg0 *C.GstAudioSrc) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_prepare
func _gotk4_gstaudio1_AudioSrc_prepare(carg0 *C.GstAudioSrc, carg1 *C.GstAudioRingBufferSpec) (cret C.gboolean) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_reset
func _gotk4_gstaudio1_AudioSrc_reset(carg0 *C.GstAudioSrc) {
	panic("unimplemented")
}

//export _gotk4_gstaudio1_AudioSrc_unprepare
func _gotk4_gstaudio1_AudioSrc_unprepare(carg0 *C.GstAudioSrc) (cret C.gboolean) {
	panic("unimplemented")
}

