package video

/*
#include <gst/gst.h>
*/
import "C"

import (
	"errors"
	"unsafe"

	"github.com/go-gst/go-gst/gst"
)

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func wrapGerr(gerr *C.GError) error {
	defer C.g_error_free(gerr)
	return errors.New(C.GoString(gerr.message))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreCaps(caps *gst.Caps) *C.GstCaps {
	return (*C.GstCaps)(unsafe.Pointer(caps.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreCapsFeatures(feats *gst.CapsFeatures) *C.GstCapsFeatures {
	return (*C.GstCapsFeatures)(unsafe.Pointer(feats.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreElement(elem *gst.Element) *C.GstElement {
	return (*C.GstElement)(unsafe.Pointer(elem.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreEvent(event *gst.Event) *C.GstEvent {
	return (*C.GstEvent)(unsafe.Pointer(event.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreMessage(msg *gst.Message) *C.GstMessage {
	return (*C.GstMessage)(unsafe.Pointer(msg.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreQuery(query *gst.Query) *C.GstQuery {
	return (*C.GstQuery)(unsafe.Pointer(query.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreSample(sample *gst.Sample) *C.GstSample {
	return (*C.GstSample)(unsafe.Pointer(sample.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func fromCoreStructure(structure *gst.Structure) *C.GstStructure {
	return (*C.GstStructure)(unsafe.Pointer(structure.Instance()))
}

//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func gobool(b C.gboolean) bool { return int(b) > 0 }
