package video

/*
#include <gst/gst.h>
#include <gst/video/video.h>
*/
import "C"

import (
	"unsafe"

	"github.com/go-gst/go-gst/gst"
)

// CropMetaInfo contains extra buffer metadata describing image cropping.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
type CropMetaInfo struct {
	ptr *C.GstVideoCropMeta
}

// GetCropMetaInfo returns the default CropMetaInfo.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func GetCropMetaInfo() *CropMetaInfo {
	meta := C.gst_video_crop_meta_get_info()
	return &CropMetaInfo{(*C.GstVideoCropMeta)(unsafe.Pointer(meta))}
}

// Instance returns the underlying C GstVideoCropMeta instance.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) Instance() *C.GstVideoCropMeta {
	return c.ptr
}

// Meta returns the parent Meta instance.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) Meta() *gst.Meta {
	meta := c.Instance().meta
	return gst.FromGstMetaUnsafe(unsafe.Pointer(&meta))
}

// X returns the horizontal offset.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) X() uint { return uint(c.Instance().x) }

// Y returns the vertical offset.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) Y() uint { return uint(c.Instance().y) }

// Width returns the cropped width.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) Width() uint { return uint(c.Instance().width) }

// Height returns the cropped height.
//
// Deprecated: This is handwritten and will be removed in a future version. Please use the autogenerated bindings instead.
func (c *CropMetaInfo) Height() uint { return uint(c.Instance().height) }
